### ISSUE TITLE
devDependencies

### ISSUE THREAD

**Issue by wcjr** [ItalyPaleAle/svelte-spa-router#10]
Mind if we update the docs to utilize `devDependencies` instead of `dependencies`?  I'll be happy to do a PR for it but it seems so small I'm not sure you need one for it.

It's one of the things I am so drawn to Svelte about, the `devDependencies` of it all!

**Comment by ItalyPaleAle** [comment]
Good point. I think that with situations like Webpack, svelte, etc, the line line between dependencies and devDependencies isn’t always clear. There certainly are situations where svelte should be included as a “production” dependency.

How about we give it as an option and let the user decide based on their situation? Feel free to submit a PR :)

**Comment by wcjr** [comment]
I'm not aware of those situations where one would need Svelte as a production dependency, my understanding is that it was used during the build process and then you were left with plain old javascript, no svelte...but I'm new to it and will take your word for it. 

I'll submit the PR shortly for the change I'm suggesting.

Thanks!

**Comment by ItalyPaleAle** [comment]
One example is when you build an app that has both front-end and back-end. The “start” script usually rebuilds the front end too. In this case, you might want to put svelte as a prod dependency.

**Comment by wcjr** [comment]
oh ok, I could see that.  Here's the only suggestion I'm making:  https://github.com/ItalyPaleAle/svelte-spa-router/pull/11

Thanks for considering!

**Comment by ItalyPaleAle** [comment]
Ok so I've been thinking about this for the last while and I believe I'd actually prefer to remove `--save` from the command.

1. People will likely have a preference on whether they want to save this as a dependency or devDependency. It depends on how their app is built, on their preference, and on whatever other reason. I expect developers at this point to be at least familiar enough with NPM to make this decision on their own and I shouldn't be spoon-feeding them!
2. Recent versions of NPM save packages in the package.json file (if present) by default, so actually `--save` is redundant.

I'm going to make the change and close the PR and the issue. Regardless, I'd like to thank you for bringing this to my attention and sparking a good conversation and giving me the opportunity to think about it 😄

**Comment by wcjr** [comment]
Nice chatting with you, appreciate your responsiveness.
