### ISSUE TITLE
Google isn't able to crawl this router

### ISSUE THREAD

**Issue by chovy** [ItalyPaleAle/svelte-spa-router#100]
I have other sites using svelte-router and it crawls just fine. svelte-spa-router isn't getting crawled by googlebot. only the home page.

**Comment by ItalyPaleAle** [comment]
This is not uncommon when using [hash-based routing](https://github.com/ItalyPaleAle/svelte-spa-router#hash-based-routing) and it’s how search engines work.

This router is optimized for SPA’s such as SaaS and others where search engine crawling isn’t required. If you need that, then a PWA (which isn’t supported by this router) might be a better option for you.

**Comment by frederikhors** [comment]
@ItalyPaleAle thanks for always being so kind, calm and precise in your answers. Even to questions that have nothing to do with this project.
