### ISSUE TITLE
Use Svelte store for params

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#105]
@ItalyPaleAle maybe this is a "revolutionary" idea!

@pateketrueke had it here: https://github.com/pateketrueke/yrv/issues/40#issuecomment-612526432.

Basically we could use a Svelte store for params for the current route and avoid to pass params to remove `<PageX> was created with unknown prop 'params'` warnings at all.

What do you think about?

**Comment by ItalyPaleAle** [comment]
I think it’s definitely a good idea, BUT it is also a major breaking change.

I don’t know if this change would get more people upset?

**Comment by frederikhors** [comment]
v3.0.0 😄 

We are happy!

**Comment by ItalyPaleAle** [comment]
I get semver and v3.0.0....  But I think this needs more discussion. Last week this module had 1,170 downloads, and I need to consider everyone's needs. Is a warning only at dev time worse than a large breaking change for thousands of apps?

I also think we should at least wait for https://github.com/sveltejs/svelte/issues/4649 and https://github.com/sveltejs/svelte/issues/4652 before making any decision

**Comment by frederikhors** [comment]
I agree. 😃

**Comment by TorstenDittmann** [comment]
I totally agree with @frederikhors here! I would very likely take advantage of that 👍 

Even though it is a breaking change, it probably only changes syntax and not a lot of logic.

**Comment by ItalyPaleAle** [comment]
I've been thinking about this more. I still don't think this is worth making the change.

I understand that it's "just a syntax change", but it will require possibly thousands of apps to be updated. I cannot do that to our users, not without a solid reason! A lot of people will rush to update the module from 2.x to 3.x, sometimes automatically (how many people put `*` as version in package.json!).

I still consider this as something that needs to be fixed upstream by Svelte. Even without a fix, this is just a warning when running in development, so it has no impact on the functionality of the solution.

There's also the simple workaround of defining a `params` prop even if you don't need it.

**Comment by frederikhors** [comment]
Dear @ItalyPaleAle,

I am really sad for this news. 😢

I was hoping it could be done in version 3.
After all semver is just what this is for: **to indicate breaking changes**!

> A lot of people will rush to update the module from 2.x to 3.x, sometimes automatically (how many people put * as version in package.json!).

I think this shouldn't concern us. We are making here **the best router for Svelte 3 now and for years to come**!

I hope you can reconsider, really, please.

And I could provide all the help you need for writing a docs explaining the migration from 2 to 3 (although I think the work will be minimal!).

Please reconsider this (perhaps hasty) summer thought.

Fred,
a huge fan of yours.
