### ISSUE TITLE
What happens when a nested router does't find a route?

### ISSUE THREAD

**Issue by PierBover** [ItalyPaleAle/svelte-spa-router#106]
Does the top parent router go to the catch all route?

**Comment by ItalyPaleAle** [comment]
No, when a nested router doesn't find a route, it doesn't impact the outer router. For the outer router, there's still a match (the fact that the nested router is shown is a sign that there's a match).

**Comment by PierBover** [comment]
For the users there is only a single URL though.

What would be the way to redirect the user to an error page if any of the sub routers fail to find a match?

**Comment by ItalyPaleAle** [comment]
You could create a `*` route in your nested router that calls `replace()` and sends people to another "not found" route.

What is the structure of your routers and routes? Maybe there can be other ways too.

**Comment by PierBover** [comment]
Thanks for the suggestion.

I'm just evaluating Svelte routers before I decide which one to use.
