### ISSUE TITLE
URL params should be decoded

### ISSUE THREAD

**Issue by jesseskinner** [ItalyPaleAle/svelte-spa-router#107]
If I have a route like `#/path/:param` and my URL is `#/path/My%20Param`, I would expect the param value to be "My Param" but it ends up as "My%20Param", forcing me to run `decodeURIComponent` on each value.

Is this expected behaviour, or a bug in svelte-spa-router?

**Comment by ItalyPaleAle** [comment]
I have noticed it myself in a couple of apps I built.

I would say it was not an intentional behavior, but in the apps I built I've fixed it in the application code.

At this stage, however, I wonder if a fix for this in the router would have to be considered a breaking one, so something that would require a version 3.

**Comment by frederikhors** [comment]
Version 3 with my beloved https://github.com/ItalyPaleAle/svelte-spa-router/issues/105 and https://github.com/ItalyPaleAle/svelte-spa-router/issues/105! 😄 😄 😄

**Comment by frederikhors** [comment]
Can we create a project here: https://github.com/ItalyPaleAle/svelte-spa-router/projects?

**Comment by ItalyPaleAle** [comment]
Let's discuss #105 separately... As i mentioned in that issue, I am waiting for changes upstream (and I still think they should fix it upstream first). While both are breaking changes, the impact is stunningly different.

**Comment by ItalyPaleAle** [comment]
@jesseskinner Thinking more about it, this makes sense. I've accepted this and will implement it for 3.0.
Thanks for the suggestion!

**Comment by ItalyPaleAle** [comment]
Fixed in branch v3.0-wip. Will be merged to master when I'm ready to release 3.0

**Comment by jesseskinner** [comment]
@ItalyPaleAle that's great, thanks!
