### ISSUE TITLE
Broken on codesandbox, can we fix or can we not?

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#108]
I'm using this amazing router on many Codesandbox projects to show issues in other svelte's projects.

I have to report an oddity that is happening on Codesandbox.

**Reproduction steps**:

1. go to [this CSB REPL](https://codesandbox.io/s/svelte-spa-router-cannot-read-property-removechild-of-null-mfy1s)

1. navigate from "Home" to "Posts"; it works, but

1. as soon as I edit something and try to change the page I get the error below:

```
TypeError
Cannot read property 'removeChild' of null
```

![image](https://user-images.githubusercontent.com/41120635/79968270-29394e80-8490-11ea-85b4-c6cc5a82bb16.png)

Is there anything we can do?

**Comment by ItalyPaleAle** [comment]
I took a look at your codesanbox. I can reproduce it, but the error stack trace makes it look like this is not an issue with the router itself, but rather with the compiled code.

I don't know if this is more of a downstream issue (codesandbox) or upstream (the Svelte compiler), but I don't think this is something I can work on…

Can you try opening an issue with codesandbox and see what they can do?

**Comment by frederikhors** [comment]
Done: https://github.com/codesandbox/codesandbox-client/issues/3974.
