### ISSUE TITLE
Child out transition block navigation

### ISSUE THREAD

**Issue by nnfans** [ItalyPaleAle/svelte-spa-router#111]
Any `out` transition nested in component route will block the navigation
It would be great if out transition canceled whenever navigate to other page

Currently I just use the `in` transition at any component inside route component

**Comment by nnfans** [comment]
Oh I forgot to add `|local` modifier

closed

**Comment by mustofa-id** [comment]
Hi,
Facing this issue, trying add `local` modifier doesn't work for me.

![spa-router](https://user-images.githubusercontent.com/25121822/98058319-f2001d00-1e76-11eb-9b23-9bc29d749901.gif)

### Code

- Component
```svelte
<script>
  import { fade } from 'svelte/transition'
</script>

<svelte:head>
  <title>About</title>
</svelte:head>

<section transition:fade|local>
  <h1>About Page</h1>
</section>
```

- Routes
```js
export default {
  '/': Index,
  '/blog': Blog,
  '/blog/:slug': wrap({
    asyncComponent: () => import('./routes/blog/Blog.svelte')
      .then((component) => new Promise((resolve) => {
        setTimeout(() => resolve(component), 2000)
      })),
    loadingComponent: Loading,
    loadingParams: {
      message: 'content'
    },
  }),
  '/about': About,
  '*': Fallback
}
```

### Dependencies Versions
```json
"svelte-spa-router": "^3.0.5"
"svelte": "^3.0.0"
```

**Comment by ItalyPaleAle** [comment]
This is not an issue with the router but rather with the way transitions work in Svelte (and the way the DOM works). You should only set either `in` or `out` transitions, but not both.
