### ISSUE TITLE
Pre-conditions (route guards) to handle close modal

### ISSUE THREAD

**Issue by Tazeg** [ItalyPaleAle/svelte-spa-router#112]
Hello, svelte-spa-router is really fine and works as expected. Thank you.

But I need to handle the browser history back to close a modal.
So i have read the doc at https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#route-pre-conditions

I have a store variable which tells me if I accept to route or not.

If not, I expected "svelte-spa-router" to do nothing. Sure it does not load any route but it seems to unload the current component.

With Vue I dit it like this : 

```js
router.beforeEach((to, from, next) => {
  if (store.state.isOpenModal) {
    store.state.isOpenModal = false // close modal
    next(false) // cancel routing
    return
  }
  next() // accept routing
})
```

This works perfectly even if I don't understand how they prevent onpopstate().
I transposed like this in Svelte : 

```js
const routes = {
  '/': wrap(
    Home,
    () => { return nextOrNot() }
  ),
  '/about': wrap(
    About,
    () => { return nextOrNot() }
  )
}

function nextOrNot () {
  if (isOpenModal) {
    iisOpenModal.set(false)
    return false
  }
  return true
}
```
My modal is closed but my current component is gone.

**Comment by ItalyPaleAle** [comment]
Thanks for bringing up this issue.

You’re right in pointing out that no component is loaded, but this is the intended behavior. The router can’t stop a page navigation, and this is a limitation in JavaScript itself. We can not prevent a user from clicking the back button, for example.

One option for you could be to invoke in the route guard function the “replace” method, just before returning false (replace, push and pop operate in the next tick of the event loop, so they’re fine to be used in that context). 

This will cause the component to be unloaded and re-loaded however, so state changes might be lost.

**Comment by Tazeg** [comment]
> The router can’t stop a page navigation, and this is a limitation in JavaScript itself.

Yes, i have read about that but i confirm that the Vue.js code really works. But I can't help to tell how it works.

> We can not prevent a user from clicking the back button, for example.

Sure, but I'd like to handle it : close the modal and do nothing else.

> This will cause the component to be unloaded and re-loaded however, so state changes might be lost.

That's exactly what i don't want. I have a page with a component state. I open a modal. When the user click the browser back navigation button. I just want no close the modal. Not so easy finally...

**Comment by ItalyPaleAle** [comment]
I'll take a look at this and see what can be done

**Comment by Tazeg** [comment]
I found a simple workaround. Finally, in that specific case it is not related to a router.

If it helps. Here was my case : I created a full page component (usually called dialog or modal) to display a "About" page.

`About.svelte`

```html
<script>
import { isOpenAbout } from './store.js'

export function show () {
  isOpenAbout.set(true)
}

export function hide () {
  isOpenAbout.set(false)
}
</script>

{#if $isOpenAbout}
  <!-- dialog html -->
  <button on:click={hide}>Close</button>
{/if}
```

As the about page can be launched anywhere in the app, we keep track of the `isOpenAbout` boolean value in the store.js : 

```js
import { writable } from 'svelte/store'
export const isOpenAbout = writable(false)
```

Anywhere in the app we can show the About page : 

```html
<script>
import About from './About.svelte'
let cmpAbout
function showAboutPage () {
  cmpAbout.show()
}
</script>

<About bind:this={cmpAbout} />
<button on:click={showAboutPage}>About</button>
```

At this point, when the user click the browser back button, we want to close the modal and stay at the current page. As we can't cancel the history back... **let's add a fake history when the modal is opened (pushState) and skip it when closed (history.go(-1))**.

Finally the workaround is just 4 lines of code :

`About.svelte`

```js
//...
export function show () {
  history.pushState({ key: 'about' }, '', '') // <========
  isOpenAbout.set(true)
}

export function hide () {
  history.go(-1)  // <========
  isOpenAbout.set(false)
}
//...
```

`App.svelte` :

```html
<script>
  import Router from 'svelte-spa-router'
  import { routes } from './routes'
  import { isOpenAbout } from './store'
  
  // called whenever the history change
  function handlePopstate () {  // <========
    if ($isOpenAbout) { isOpenAbout.set(false) } // <========
  }
</script>

<Router {routes} />
<svelte:window on:popstate={handlePopstate}/>
```

**Comment by ItalyPaleAle** [comment]
Sorry for the delay in responding, I've been incredibly busy for the last few weeks.

I'm really glad to hear you were able to find a simple, yet effective, workaround! Thanks for sharing it with us

**Comment by avimar** [comment]
This is the closest I can find to my question: Before navigation, on the `routeLoading` event I wonder if I can cancel it, e.g. `preventDefault()`?

My use case: I have a form and have noticed the user has unsaved modifications. How do I prevent/alert on navigation away, and prompt them to save their changes (or discard?)
Similar to the `onunload` event for the body, which I _assume_ doesn't apply when using the router.

Thanks!

**Comment by ItalyPaleAle** [comment]
In the form, do the validation before it's submitted, then you can block the navigation.

So:

1. The form has `on:submit|preventDefault={handler}` attribute so that it invokes `handler()` when the user submits it
2. The handler validates the form
3. If everything is fine, then use `push()` to send the user to a new page
4. If it fails, just `return false` and nothing will happen (the `preventDefault` modifier prevents the form to submit)

**Comment by avimar** [comment]
Right, that works for submitting a form with errors.

I'm asking about unsaved data, eg. the form is dirty and the user clicked to navigate away. I'd like to interrupt that.
Thanks for your time!

**Comment by ItalyPaleAle** [comment]
I'm not sure how I would do that, I'd have to experiment.

One lead (which might or might not work) could be using a route guard to block the new component from mounting if the form is dirty, and inside the route guard invoke `push()` to send the user back to the page they were on before. This would likely still cause the component to be un-mounted, so you'd have to restore the state of the form manually.
