### ISSUE TITLE
Route Guards not identifying variable change

### ISSUE THREAD

**Issue by Christheoreo** [ItalyPaleAle/svelte-spa-router#115]
Hi,

first of all - I love Svelte-Spa-Router and I think it's awesome.

I am having some issues with Route Guards for authentication.

I am using stores to store and change my authentication value, once the user is authenticated the store value will be set to true and then I will use `replace()`  to change the URL to show a different page. The problem is that it always thinks the value is false, when the console logs show that the value is true.

Here is the base code
Note I am using a prefix of '/admin'

```

 let authenticated = false;
 let isLoggedInSub;

 const routes = {
    // Exact path
    // "/": Dashboard,
    "/": wrap(
      Dashboard,
      { foo: "bar", auth: authenticated },
      () => {
        return authenticated;
      }
    ),
    // Using named parameters
    "/login": Login,
    // Catch-all - if present it must be the last
    "*": NotFound
  };

//here is an example of how i set my store to true and redirect.
const routeEvent = async event => {
    let action = event.detail.action;

    if (action == "authenticated") {
      isLoggedInStore.set(true);
      console.log(`here`)
      replace("/admin/");
    }
  };

onMount(async () => {
    isLoggedInSub = isLoggedInStore.subscribe(val => {
      authenticated = val;
      console.log(
        "value has changed. now = " + (authenticated ? "true" : "false")
      );
    });
  });

 onDestroy(() => {
    //unsubscribe
    isLoggedInSub();
  });
```

Please see my screenshot for logs from Chrome (crossed out irrelevant log)
![image](https://user-images.githubusercontent.com/41023695/82072001-ca51a880-96ce-11ea-8cc4-9b529e69cb44.png)

If I am using this wrong, please can you point me in the right direction?

**Comment by ItalyPaleAle** [comment]
Sorry for the delay in responding, I've been really busy with work.

This looks like a really interesting issue and I'm trying to figure it out. One thing I don't really understand is the purpose of this line:

```
{ foo: "bar", auth: authenticated },
```

This passes the `authenticated` variable by value when the route guard is created (when the routes object is created), but it doesn't look like you're using it anywhere. Is this just leftover code from various debugging exercises?

If you place a `console.log(authenticated` before this line `return authenticated;`, what do you see?

**Comment by Christheoreo** [comment]
Hi - I will try what you said about the console.log once I have access to my laptop - the 
```
{ foo: "bar", auth: authenticated },
```
Was just to test what would come through - no real purpose what so ever!

**Comment by ItalyPaleAle** [comment]
Ok, let me know what the result is. If you can also share some more code that would be very helpful!

**Comment by Christheoreo** [comment]
Hi - I realised the issue! 
After testing your console log suggestion I relaised the events wern't firing in the correct order.

I needed to do the actual subscribing part outside of the onMount method! I assumed it was good practise to keep everything in the `onMount` method but I guess that way it would execute after the route guard!

This was my final working code (modified slightly)

```
let authenticated = false;
  let isLoggedInSub;

  isLoggedInSub = isLoggedInStore.subscribe(val => {
    authenticated = val;
    console.log(
      "value has changed. now = " + (authenticated ? "true" : "false")
    );
  });
  const prefix = "/admin";
  const routes = {
    // Exact path
    // "/": Dashboard,
    "/": wrap(Dashboard, () => {
      console.log(`Auth value = ${authenticated ? "True" : "FALSE"}`);
      if (!authenticated) {
        replace("/login");
      }
      return authenticated;
    }),
    // Catch-all - if present it must be the last
    "*": NotFound
  };

  //here is an example of how i set my store to true and redirect.
  const routeEvent = async event => {
    let action = event.detail.action;
  };

  onMount(async () => {
    //
  });

  onDestroy(() => {
    //unsubscribe
    isLoggedInSub();
  });
```

Sorry for wasting your time! Thank you for your help :D

**Comment by ItalyPaleAle** [comment]
Ohhh that's very interesting. Thanks for debugging that and reporting on your findings! Glad you could make it work 😄
