### ISSUE TITLE
Should the router be installed as a dependency or a dev dependency?

### ISSUE THREAD

**Issue by pensierinmusica** [ItalyPaleAle/svelte-spa-router#118]
Hi,

The Svelte official template installs the `svelte` package as a dev dependency:

https://github.com/sveltejs/template/blob/master/package.json

This router should also be installed as a dev dependency or as a regular dependency instead?

Thanks!

**Comment by ItalyPaleAle** [comment]
See https://github.com/ItalyPaleAle/svelte-spa-router/issues/10

It depends on your scenario and preferences. Either works :)
