### ISSUE TITLE
Redirect from routes definition

### ISSUE THREAD

**Issue by pensierinmusica** [ItalyPaleAle/svelte-spa-router#119]
Hi,

Using this module is there a convenient way to make a certain route redirect to another?

```js
const routes = {
  '/hello': Hello,
  '/': // redirect to "/hello"
};
```

Note that I don't want to just render the `Hello` page, I want the browser to redirect to the `/hello` route.

Thanks for your help!

**Comment by ItalyPaleAle** [comment]
You can use the “replace” method inside a route guard (check the Advanced Docs) to do this. Or you can create a “Home” route that calls “replace” after it’s initialized.

**Comment by pensierinmusica** [comment]
👍Thx!
