### ISSUE TITLE
Internet Explorer 11 support - polyfill?

### ISSUE THREAD

**Issue by avimar** [ItalyPaleAle/svelte-spa-router#120]
I'm totally not expecting anyone to want to deal with this, but it seems it's not that hard to transpile svelte for IE11. There's still some usage around the world with people that can't update. Anyway, it's an interesting learning experience.

sapper has a config, https://github.com/sveltejs/sapper-template/blob/master/rollup.config.js but I had to add to the exclude: `'node_modules/core-js/**'`
and add to the presets:
```
,useBuiltIns: 'usage'
,corejs: 3 //npm package: core-js
```
Which you should be able to see here: https://github.com/sveltejs/svelte/issues/2621#issuecomment-500714127

Here's the errors I've been able to pry out of IE11:
```
{
   [functions]: ,
   __proto__: { },
   description: "Object doesn't support this action",
   message: "Object doesn't support this action",
   name: "TypeError",
   number: -2146827843,
   stack: "TypeError: Object doesn't support this action
   at Anonymous function (http://localhost:3030/build/bundle-sim-activate-es2015.js:14337:6)
   at Anonymous function (http://localhost:3030/build/bundle-sim-activate-es2015.js:2447:14)
   at flush (http://localhost:3030/build/bundle-sim-activate-es2015.js:2256:10)",
   Symbol()_6.2t20egsw6sf: undefined,
   Symbol()_k.2t20egsw6vn: undefined,
   Symbol(__feathersActivateHooks)_g.2t20egsw6vn: undefined,
   Symbol(Symbol._hidden)_h.2t20egsw6vn: undefined,
   Symbol(Symbol.hasInstance)_i.2t20egsw6vn: undefined,
   Symbol(Symbol.search)_j.2t20egsw6vn: undefined
}
```
bundle-sim-activate-es2015.js:14337:  	   ` window.dispatchEvent(new Event("hashchange"));` inside of `function replace$2(location) {`

Pollyfilling with [custom event](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill) doesn't seem to change anything.

When I remove  ` window.dispatchEvent(new Event("hashchange"));` then we don't get any errors, we just get a redirect to the base page like other time. IE11 should be supporting pushstate... https://caniuse.com/#feat=mdn-api_history_pushstate

I'll make it live for anyone that wants to play with it in IE 11 (seems it's on all windows 10 machines): https://freedomhot.com/sim-activate.html
It redirects you to https://freedomhot.com/sim-activate.html#/1 which is then blank, but if you reload, then it works. Again, one of the things that works in modern browsers.

Any ideas?

**Comment by ItalyPaleAle** [comment]
I can't make changes without the source code, but the polyfill you're using seems different than what written here: https://stackoverflow.com/a/26596324/192024 which I haven't tried, but lots of people seem to suggest it works. In particular, in your bundle you included a polyfill twice, but changing the methods.

Can you try with just this code (copied from SO):

```js
(function () {
  if ( typeof window.CustomEvent === "function" ) return false; //If not IE

  function CustomEvent ( event, params ) {
    params = params || { bubbles: false, cancelable: false, detail: undefined };
    var evt = document.createEvent( 'CustomEvent' );
    evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
    return evt;
   }

  CustomEvent.prototype = window.Event.prototype;

  window.CustomEvent = CustomEvent;
  window.Event = CustomEvent;
})();
```

Note the second-last line where I'm polyfilling window.Event too.

PS: Because this is not an issue with the router, but rather with a polyfill, I'm going to close this issue for now. There's nothing I can do on the router to fix this issue anyways.
