### ISSUE TITLE
Hash missing on use:link when in dynamic array

### ISSUE THREAD

**Issue by jayliu50** [ItalyPaleAle/svelte-spa-router#122]
Hi, I'm experiencing an issue having to do with `use:link` seemingly not working as expected.

I have a dynamic number of page items.
An `{#each}` loop is tied to the dynamic list of items.
When items in the list get deleted, sometimes, the _other_ items in the list will "lose" the # in their href.
So for example, `"#/page/123"` will turn into `"/page/123"` after another sibling has been deleted.

I have a repl here showcasing the issue: https://svelte.dev/repl/2fd16ed03ef740f182ed056603057c59?version=3.23.2 

Steps to follow

1. Create a good 5-6 Pages
2. Select an item (I usually go in the middle of the list), and delete it
3. BUG: sometimes you'll see by inspection of the URLs, that it's set to go to a URL without a `#`.

**Comment by ItalyPaleAle** [comment]
@jayliu50 thanks for this. I can reproduce it but adding some logging in the `link` method, I see that it's not being invoked (neither is the method that updates the element).

I am leaning towards this being a bug in Svelte itself. In fact, Svelte is re-creating the elements in the DOM and it's not firing the `link` action.

Can you open an issue in https://github.com/sveltejs/svelte/issues ?

**Comment by jayliu50** [comment]
Thank you so much for your reply, and for your time in looking into this.

Yes, I'll go ahead and open up an issue there. 

I was able to work around the issue by simply setting the `use:link` attribute rather than `href`

```diff
<a
+use:link={`/page/${page._id}`}
-use:link
+href
-href={`/page/${page._id}`}
use:active={{ path: `/page/${page._id}*`, className: 'active' }}>
{page.title || page._id || 'Page'}
</a>
```

**Comment by ItalyPaleAle** [comment]
Glad that worked! Otherwise, you could have also manually added a link with #:

```sh
href="#/page/{page._id}"
```

**Comment by jordaofranca** [comment]
I had the same issue with `each` logical block. It seems like it has same context. it gives a ctx[1].call not a function.

A work around is to create a standalone component that applies link to it. Like a `Link` component.
