### ISSUE TITLE
A way to do codesplitting

### ISSUE THREAD

**Issue by BogdanDarius** [ItalyPaleAle/svelte-spa-router#124]
It seems that async route loading is not working.
I tried svelte-spa-chunk and I cant get it to work(ChunkGenerator is not a function).
Is there a way to get codesplitting?

**Comment by ItalyPaleAle** [comment]
Thanks for the report.

For version 3.0 (which is behind because I've been too busy) I am planning to implement native support for dynamically loaded routes, as per #73 and #104 

In the meanwhile, because this issue is with a third-party module, may I recommend you open an issue with that repo?
