### ISSUE TITLE
Support base URL

### ISSUE THREAD

**Issue by Shyam-Chen** [ItalyPaleAle/svelte-spa-router#126]
```html
<script>
import Router from 'svelte-spa-router';
import { ChunkGenerator } from 'svelte-spa-chunk';
import ChunkComponent from 'svelte-spa-chunk/Chunk';

import Home from '~/home/Home';
import NotFound from '~/not-found/NotFound';

const Chunk = ChunkGenerator(ChunkComponent);

const routes = {
  '/': Home,
  '/hello-world': Chunk(()=> import('~/hello-world/HelloWorld')),
  '*': NotFound,
};
</script>

<!-- Support base URL -->
<Router base="/app" {routes} />
```

Ref: https://router.vuejs.org/api/#base

**Comment by ItalyPaleAle** [comment]
Hi, thanks for the proposal!

The goal of svelte-spa-router is to be as simple to use as possible, which means that we'll introduce new APIs only if they're strictly necessary or if they would save a significant amount of effort.

In this case, I'm not a fan of adding the "base" attribute for two reasons:

1. There are edge scenarios that aren't unclear. For example, in your example above, should the "NotFound" route show up when you request "/notapp"?
2. It's easily replaced by adding a prefix to the routes. In your case, it would simply require changing the URLs to `/app` and `/app/hello-world`.
