### ISSUE TITLE
history not recorded

### ISSUE THREAD

**Issue by pipboy9000** [ItalyPaleAle/svelte-spa-router#128]
I have a weird issue, i'm trying to make the back button go to the main page of my app in case user used a link to open it. for example if the user has opened my app with the url: www.domain.com/#/ABCD the app loads a page related to the ABCD id. But if a user will now click the back button the app will close, instead i want to go to www.domain.com

in my App.svelte i do this:
`  onMount(() => {      
let forwardTo = $location.split("/")[1];
    if (forwardTo) {
    replace("/");
    push("/" + forwardTo);
    }
    });`

it does forward to the requested page but when i click the back button it doesn't go to "/" 
Another strange thing that happens is that if i open a new tab and paste the url www.domain.com/#/ABCD and click on the window before the page loads (i.e i unfocuse the address bar before the main app loads right after clicking Enter) everything works as expected.

Am i missing something?

**Comment by ItalyPaleAle** [comment]
Uhm this is an interesting use case, and I'd have to try some code to give you some clear guidance.

The first thing that comes to mind is that both `replace` and `push` actually trigger the navigation on the next tick of the event loop, to ensure the rendering doesn't get messed up. This might be why the code isn't working properly?

The good news is that a few months back I added a small feature which I finally could find a use for :) Both `replace`, `push` and `pop` return a promise.

Try:

```js
let forwardTo = $location.split("/")[1];
if (forwardTo) {
    replace("/").then(() => push("/" + forwardTo))
}
```

See if this works?

PS: When using Svelte, `onMount` is usually not needed, unless you're also using SSR.... but if you were using SSR, then you probably wouldn't be using this router :)

**Comment by pipboy9000** [comment]
hey, i tried it, and also with a 2 seconds setTimeout. they both seemed to work as expected except for when clicking the back button. in all cases the problem resolved if i clicked the window before page loaded, i'm starting to think it's a chrome thing.
I checked again and this bug seem to happen only when i type the address manually, if i use a link everything seems to work fine so ill close this issue for now.
Thanks for answering :)
