### ISSUE TITLE
Question: Export as Static Site

### ISSUE THREAD

**Issue by sandrochuber** [ItalyPaleAle/svelte-spa-router#129]
Hi all,

Thanks for the cool project, I really like it!

Would this router potentially enable to build a completely static site of my application, where I don't need a server and can directly deploy to e.g. github pages, Netlify, ...?

Has anyone already done this or is there some technical difficulty that wouldn't allow this?

I know that Sapper enables this via `Sapper export` and scrapes the site for links, but we have a lot of auth-related pages, so I don't think that this will really help in that case.

**Comment by ItalyPaleAle** [comment]
Yes of course. Creating static web apps (with no server-side processing required at all) is precisely why this router exists. It's partly explained here: https://github.com/ItalyPaleAle/svelte-spa-router#hash-based-routing
