### ISSUE TITLE
Regex for params routes declaration?

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#133]
Is there a way to declare routes with params in regex using `Map()`?

```js
const prefix = '/players'

const routes = {
  '/': All,
  '/create': Create,
  '/update/:ID': Update,
  '/:ID': Open, // this one
  '/:ID/*': Open // this one
}
```

I'm not a regex expert, is there one?

**Comment by ItalyPaleAle** [comment]
The equivalent regex that matches all of `/:ID`, `/:ID/`, and `/:ID/*` should be: `/^\/(.*?)(\/(.*))?$/i` (of course, this matches `:ID` as everything, if you only have a subset of characters you can use that instead). In the result, `wild[1]` will be the value of `:ID` and `wild[3]` (if present) will be the value of `*` (without the leading `/`).

For `/create/:ID`, it's `/^\/create\/(.*)/i`

Note that even when using a Map, you can still use strings to represents paths like above, and the router will still support them.
