### ISSUE TITLE
Prevent re-render when using nested routers

### ISSUE THREAD

**Issue by BogdanDarius** [ItalyPaleAle/svelte-spa-router#136]
Version 3.0 have some awesome features and I was playing around with them.
One problem I'm facing is a way to prevent the re-render of the parent component when using **wrap asyncComponent** with nested routers.

When I click on **dashboard** I want to load the **Dashboard component**, this works as expected. 
I added a regex to match all dashboard subroutes, so when I go to **dashboard/first-menu** it renders the **FirstMenu component**, this also works but unfortunately re-renders the **Dashboard component**.
I attached a sandbox example to showcase my problem.
https://codesandbox.io/s/nice-cdn-tcrpy?file=/App.svelte

**Comment by frederikhors** [comment]
You can also avoid `import FirstMenu from "./FirstMenu.svelte"; etc...` because you're using async.

But still the re-rendering problem is here.

I know @ItalyPaleAle will come immediately here.

**Comment by BogdanDarius** [comment]
> You can also avoid `import FirstMenu from "./FirstMenu.svelte"; etc...` because you're using async.
> 
> But still the re-rendering problem is here.
> 
> I know @ItalyPaleAle will come immediately here.

Yeah I forgot them there. I tried without asyncComponent and got the same problem.

**Comment by ItalyPaleAle** [comment]
Thanks for reporting this. I think I understand what is causing this, and it's actually not just an issue with nested routers, but due to changes implemented to support async routes.

Let me try to push a fix asap.

**Comment by ItalyPaleAle** [comment]
Fixed. Version 3.0.2 coming out shortly :rocket:
