### ISSUE TITLE
Query parameters and the "active" class check?

### ISSUE THREAD

**Issue by ganigeorgiev** [ItalyPaleAle/svelte-spa-router#139]
Often when there is some filter field on the page, I add it as a query param to the url (eg. `'/#/dashboard?search=test'`) in order to keep and preset the value on page refresh.

This unfortunately removes the highlight from the active links. I guess this could be fixed by providing a proper regex to the `use:active` `path` option, but shouldn't the default behavior emulates the route matching (aka. ignoring the query parameters if are not defined in the route definition path)?

**Comment by ItalyPaleAle** [comment]
Yes it should be the default behavior, so if this doesn't happen it is likely a bug.

Thanks for the report! Let me look into this tonight.

**Comment by ItalyPaleAle** [comment]
I've looked into this, and I actually forgot this is the correct behavior.

Here's the code that is making it happen: https://github.com/ItalyPaleAle/svelte-spa-router/blob/40d82d7688ea9c04632033d4ce3c865d2f531393/active.js#L30 As you can see, it's explicitly adding the "querystring" to the path to match.

I've been doing some tinkering and I think I'd say this a feature and not a bug 😀 

- Links like `<a href="#/hello/svelte?quantity=100">` already match only the exact value, including the "querystring"
- In the tests, in fact, the line is shown as `<a href="#/hello/svelte?quantity=100" use:active={'/hello/*'}>` to make sure that it matches all cases, including the querystring

Changing the default behavior at this point would be a significant breaking change, revolutionizing the behavior of `use:active`.

My recommendation to you is to use a regex or a string ending in `*`.
