### ISSUE TITLE
Reloading a route with different params

### ISSUE THREAD

**Issue by uriberto** [ItalyPaleAle/svelte-spa-router#14]
Suppose the route #/widget/:param goes to the component Widget.
I believe that if you are at #/widget/paramA and you route to #/widget/paramB, the router does not destroy and re-load the component Widget, but rather just changes the values of params within the existing component. 

I do not know if this is the intended behavior or not, but it means that onMount is not called again, which for some components is a critical part of their use. It would be nice to at least have the built-in option to destroy the old component and create a new one in this case, so that onMount runs as expected.

**Comment by ItalyPaleAle** [comment]
Makes sense. I think I have an idea on what’s causing this, and I’ll look into it later today or tomorrow. Thanks for flagging it

**Comment by ItalyPaleAle** [comment]
So I think I understand why this behavior and while it wasn’t something done intentionally, it does make sense, as Svelte tries to change the DOM as little as possible.

I’ll look more into this later today or tomorrow.

In the meanwhile, maybe there’s a workaround for you?

- create a function named “mount”
- bind “mount” to onMount
- also add a reactive statement so every time that params change, you manually fire the “mount” function.

Would that work? Also, any chance you could create a REPL and share that?

**Comment by uriberto** [comment]
I made a quick repl with the issue and the workaround here: https://svelte.dev/repl/11e51e1ce65449c0b0db1af0906e206a?version=3.4.4

I think in the workaround method, you don't need to attach mount to onMount, because the reactive statement will work when params first gets its value, so it will run when the component is first mounted anyway.

The workaround (which is exactly what I figured out yesterday and works for my immediate purposes) also has the possible downside that you might want the route to run mount again even if you are just going back to the exact same route, thus not changing params. Maybe you want some random behavior, or maybe you want to update to get new information from the server. But since mount won't run unless the value of params changes, you won't see the update. (Evident in the repl example)

**Comment by ItalyPaleAle** [comment]
Thanks for writing the REPL, and yes I agree the solution you wrote is the optimal one.

Regarding this: 

> you might want the route to run mount again even if you are just going back to the exact same route

This is actually by design. If the navigation goes to a page with the same hash, browsers won't trigger the "hashchange" event, and so nothing happens. I actually like this behavior, as I find it makes sense for a SPA.

A workaround in your case could be to add an action to the link that changes something else in the state when clicked. You can then use that to trigger a new refresh of the view.

**Comment by lud** [comment]
Hello, 

I have the same problem. The param in my route is not updated when I change the URL, so all the code depending on the URL params must be in reactive `$:` statements. That results in code that is hard to understand.

A force-reload component option could be very useful !

**Comment by ItalyPaleAle** [comment]
I understand.

Reactive statements aren't necessarily "bad", however, as they're the core of Svelte. You could simplify them slightly by putting them into a reactive block like:

````js
$: {
    party_id = params.party_id
    client = partyConnect(party_id)
    ps = client.asSvelteStore()
}
````

**Comment by ItalyPaleAle** [comment]
I can look into a "force reload" option however. How would that need to look like to be helpful to you?

**Comment by lud** [comment]
Could it be as simple as a `refresh` attribute on the route ?

```
const routes = {
    '/': HomePage,
    '/topic/:id': { component: Topic, refresh: true }
}
```

**Comment by thiagomagro** [comment]
Guys, an easy way to achieve that is using the following code on the svelte page that need to be rerendered:

`
  $: if (params.id) { //watch the params.id for changes
    getData(); //invoke your method to reload data
  }
`

**Comment by andriytyurnikov** [comment]
Thanks guys, this is not my first issue with svelte component remounting, and such solutions look not idiomatic really. Perhaps router should deal with this issue, not routable component.
