### ISSUE TITLE
dynamic routes, Uncaught (in promise) TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#143]
I'm trying to use new 3 version.

- Issue reproduction here: https://github.com/frederikhors/svelte-spa-router-name-of-null-error.

- Gif:

![issue](https://user-images.githubusercontent.com/41120635/95003532-8cebaa00-05e0-11eb-87db-3a9f7ecf9b52.gif)

**Steps to reproduce:**

1. download reproduction (`git clone https://github.com/frederikhors/svelte-spa-router-name-of-null-error`)
1. `npm install`
1. `npm start`
1. go to http://localhost:5000
1. click on "New todo"
1. from browser DevTools Network tab change to the Slow or slower
1. click on "Todos list"
1. as soon as it downloads 1 byte click on "New todo" again
1. error in console: 

```
Router.svelte:523  Uncaught (in promise) TypeError: Cannot read property 'name' of null
```

If you use `loadingComponent` in `routes.js` the error is not catched but the router still doesn't work.

**Comment by ItalyPaleAle** [comment]
Thanks for catching this and reporting this! I've pushed a fix to the master branch and will make a release soon.

**Comment by ItalyPaleAle** [comment]
Especially, thanks for sharing the repro code and clear, precise instructions :)

**Comment by ItalyPaleAle** [comment]
v3.0.3 is out with a fix for this regression. Thanks again!!
