### ISSUE TITLE
What about "Discussions" tab?

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#145]
I have seen that you are very interested in closing issues immediately and bringing them to 0.

And that's a great thing.

How about adding the "Discussions" tab so we can talk about something other than "issues"?

Like this: https://github.com/FormidableLabs/urql/discussions.

**Comment by ItalyPaleAle** [comment]
Thanks for the suggestion!

At this stage, this project is fairly small in size and we don't really have a community like Kubernetes or other large-scale projects

I am concerned that by enabling the discussion tab, it would end up being an end-user support forum (help with user code and not with bugs in the router) whose burden would fall just on me.... and as I am maintaining this purely as a volunteer, I don't have the resources to sign up for maintaining a community and provide unpaid tech support. Sorry :(
