### ISSUE TITLE
SyntaxError: node_modules\svelte-spa-router\Router.svelte: Identifier '_asyncToGenerator' has already been declared (26:7)

### ISSUE THREAD

**Issue by jerryk1925** [ItalyPaleAle/svelte-spa-router#150]
`WARNING in ./node_modules/svelte-spa-router/Router.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
Router has unused export property 'loc'. If it is for external reference only, please consider using `export const loc` (65:11)
63:
64:
65: export var loc = readable(null, // eslint-disable-next-line prefer-arrow-callback
               ^
66: function start(set) {
67:   set(getLocation());
 @ ./src/App/index.svelte 13:0-39 25:15-21
 @ ./src/main.js

WARNING in ./node_modules/svelte-spa-router/Router.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
Router has unused export property 'location'. If it is for external reference only, please consider using `export const location` (82:11)
80:  */
81:
82: export var location = derived(loc, $loc => $loc.location);
               ^
83: /**
84:  * Readable store that returns the current querystring
 @ ./src/App/index.svelte 13:0-39 25:15-21
 @ ./src/main.js

WARNING in ./node_modules/svelte-spa-router/Router.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
Router has unused export property 'querystring'. If it is for external reference only, please consider using `export const querystring` (87:11)
85:  */
86:
87: export var querystring = derived(loc, $loc => $loc.querystring);
               ^
88: /**
89:  * Navigates to a new page programmatically.
 @ ./src/App/index.svelte 13:0-39 25:15-21
 @ ./src/main.js

ERROR in ./node_modules/svelte-spa-router/Router.svelte
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\xxx\lilit\node_modules\svelte-spa-router\Router.svelte: Identifier '_asyncToGenerator' has already been declared (26:7)

  24 | import { readable, derived } from "svelte/store";
  25 | import _asyncToGenerator from "@babel/runtime/helpers/asyncToGenerator";
> 26 | import _asyncToGenerator from "@babel/runtime/helpers/asyncToGenerator";
     |        ^
  27 | import { createEventDispatcher, afterUpdate } from "svelte";
  28 | import regexparam from "regexparam";
  29 | 
    at Parser._raise (C:\xxx\lilit\node_modules\@babel\parser\lib\index.js:766:17)
    at Parser.raiseWithData (C:\xxx\lilit\node_modules\@babel\parser\lib\index.js:759:17)
    at Parser.raise (C:\xxx\lilit\node_modules\@babel\parser\lib\index.js:753:17)
    at ScopeHandler.checkRedeclarationInScope (C:\xxx\lilit\node_modules\@babel\parser\lib\index.js:4873:12)
    at ScopeHandler.declareName (C:\xxx\lilit\node_modules\@babel\parser\lib\index.js:4839:12)
    at Parser.checkLVal (C:\xxx\lilit\node_modules\@babel\parser\lib\index.js:9422:22)
    at Parser.parseImportSpecifierLocal (C:\xxx\lilit\node_modules\@babel\parser\lib\index.js:12829:10)
    at Parser.maybeParseDefaultImportSpecifier (C:\xxx\lilit\node_modules\@babel\parser\lib\index.js:12874:12)
    at Parser.parseImport (C:\xxx\lilit\node_modules\@babel\parser\lib\index.js:12800:31)
    at Parser.parseStatementContent (C:\xxx\lilit\node_modules\@babel\parser\lib\index.js:11531:27)
 @ ./src/App/index.svelte 13:0-39 25:15-21
`

`                        preprocess: require('svelte-preprocess')({
                            babel: {
                                presets: [
                                    [
                                        '@babel/preset-env',
                                        {
                                            modules: false,
                                            targets: {
                                                node: 14,
                                                esmodules: true,
                                            },
                                        },
                                    ],
                                ],
                                plugins: ['@babel/plugin-syntax-dynamic-import', '@babel/plugin-transform-runtime']
                            }}),`

**Comment by ItalyPaleAle** [comment]
Thanks for the report. However, there is not much we can do with just an error message like these. Can you please provide more context so we have something to inspect? 

Best practices for reporting an issue include:

1. Reporting what you were trying to do
2. Reporting what you were expecting to see
3. Include steps to reproduce the issue

The last is very important, as without your code (or a code that can reproduce the issue) it's often very hard to understand the issue.

**Comment by jerryk1925** [comment]
i want use dynamic import for my routes, and my webpack show error 
` Identifier '_asyncToGenerator' has already been declared (26:7)`
My webpack config

`            {
                test: /\.(js|msj|svelte)$/,
                exclude: /node_modules\/(!svelte)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env']
                    }
                }
            },
            {
                test: /\.svelte$/,
                exclude: /node_modules\/(?!svelte)/,
                use: {
                    loader: 'svelte-loader',
                    options: {
                        emitCss: true,
                        hotReload: true,
                        preprocess: require('svelte-preprocess')({
                            babel: {
                                presets: [
                                    [
                                        '@babel/preset-env',
                                        {
                                            modules: false,
                                            targets: {
                                                node: 14,
                                                esmodules: true,
                                            },
                                        },
                                    ],
                                ],
                                plugins: ['@babel/plugin-syntax-dynamic-import', '@babel/plugin-transform-runtime']
                            },
                            postcss: {
                                postcssOptions: {
                                    plugins: [
                                        [
                                            'postcss-preset-env',
                                            {
                                                browsers: 'last 5 versions',
                                                autoprefixer: { grid: true },
                                                stage: 0,
                                            },
                                        ],
                                        'postcss-import',
                                    ]
                                }
                            },
                        })
                    },
                },
            },`

**Comment by ItalyPaleAle** [comment]
Sorry for responding late.

I still don't have a complete repo to try, but I see that you're using babel extensively. This is likely an issue with Babel or with your setup above.

svelte-spa-router is a bit different from other modules on NPM as we publish "raw" (uncompiled) Svelte files. So, if you're excluding svelte from Babel's processing, you might need to treat the router the same way. But this is just a guess…
