### ISSUE TITLE
National characters (like ščřť) handling

### ISSUE THREAD

**Issue by thubalek** [ItalyPaleAle/svelte-spa-router#151]
I'm trying to understand whether SPA handles special characters like in path `ščřť` correctly and I have feeling it does not. Please note I'm quite new to Svelte so there may be issue on my side. 

What I did: 

I created simple component `Test.svelte`

```
<script>
    export let params;
</script>

<h1>Param value is {params.value}</h1>
```

Added it into routes 

```
import TestX from "./routes/Test.svelte"
routes = {
    ...
   '/test/:value': TestX
}
```

and when I invoke url  `http://localhost:8080/app/index.html#/test/š` I get 

`Param value is %C5%A1`

So is  

`<h1>Param value is {decodeURIComponent(params.value)}</h1>`

intended solution?

**Comment by ItalyPaleAle** [comment]
What version of the package are you using? In version 3, I made a change so `decoreURIComponent` is performed automatically and you shouldn't need to run it yourself. See: https://codesandbox.io/s/zen-sanderson-duqhx

If you're on version 2, then yes, that's the correct behavior.

**Comment by thubalek** [comment]
I'm using 2.1.0. That's probably root cause. Thanks for your help. It makes sense to me now.
