### ISSUE TITLE
Support path params in RegExp path format

### ISSUE THREAD

**Issue by vigenere23** [ItalyPaleAle/svelte-spa-router#154]
When declaring a route in the `Regexp` format, there's no way to include route params. I've checked the source code for `regexparam` and it seems to act quite weirdly with RegExp inputs (returning `false` as keys? non-sens...). That means the situation needs to be handled manually on our side by literally iterating through the RegExp string.

**Comment by ItalyPaleAle** [comment]
Is this related to #153?

If not, Can you please give me an example of what you're trying to achieve?

**Comment by vigenere23** [comment]
> Is this related to #153?

Yes, sorry, I've just added a magic comment to link them :)

**Comment by ItalyPaleAle** [comment]
Ok I'm going to close this then so we can track work on the PR.
