### ISSUE TITLE
use:active possible TS bug?

### ISSUE THREAD

**Issue by Sidewinder1138** [ItalyPaleAle/svelte-spa-router#162]
I'm using svelte-spa-router in a Svelte project with TypeScript. It's working great, and I just started using the 'use:active' ability. It works, but I get this TS error:

Argument of type 'typeof import("c:/Users/ander/work/nova/fresh/apps/flare2/node_modules/svelte-spa-router/active")' is not assignable to parameter of type 'SvelteAction<[{ path: string; className: string; }], HTMLAnchorElement>'.
  Type 'typeof import("c:/Users/ander/work/nova/fresh/apps/flare2/node_modules/svelte-spa-router/active")' provides no match for the signature '(node: HTMLAnchorElement, args_0: { path: string; className: string; }): void | { update?: (args_0: { path: string; className: string; }) => void; destroy?: () => void; }'.ts(2345)

Any help would be appreciated, I'm really having trouble even beginning to debug this...

**Comment by ItalyPaleAle** [comment]
Can you please show the line (and the rest of the relevant code) where this is happening?

**Comment by Sidewinder1138** [comment]
Sure! This is the code that is creating my <a> tags:
`  {#each pages as page}
    <a href={page.href}
      use:link
      use:active={{ path: page.href + '(\/.*)?', className: 'flareNavSelected' }}
    >
      <Icon i={page.icon} fixedWidth/>
      <span class="hide-tablet">{page.label}</span>
    </a>
  {/each}`

Earlier in the component I define an array of 'pages' like this:
`const pages = [
  {
    label: 'Home',
    icon: 'home',
    href: '/',
  },
  {
    label: 'Warehouses',
    icon: 'warehouse',
    href: '/warehouses',
  },
...
`

**Comment by Sidewinder1138** [comment]
The error is on the 'use:active' part.

**Comment by ItalyPaleAle** [comment]
Sadly I cannot reproduce it.

What version of svelte-spa-router are you using? And what version of TS?

**Comment by Sidewinder1138** [comment]
"svelte-spa-router": "^3.0.5",
"typescript": "^3.9.3"

**Comment by ItalyPaleAle** [comment]
I'm using the same versions. I still cannot reproduce this... Are you able to share the entire component? Also, have you tried deleting the node_modules folder and re-installing the modules from npm?

**Comment by Sidewinder1138** [comment]
Ok I've been able to repro this with a totally fresh minimal app: https://github.com/Sidewinder1138/router-bug-repro

**Comment by ItalyPaleAle** [comment]
Thanks a lot for this repo! This is very helpful. I wasn't trying "npm run validate" and it always worked with "npm run dev".

Looks like there's indeed an issue with the typings. I'll fix it tonight.

**Comment by Sidewinder1138** [comment]
My pleasure, and thanks! Really love svelte-spa-router, it's been incredibly helpful for my app 👍

**Comment by ItalyPaleAle** [comment]
Thanks, @Sidewinder1138 ! And thanks again for reporting this

The issue should be fixed in master and I'll make a release in a few days once I finish a few more things :)

**Comment by Sidewinder1138** [comment]
My pleasure, and thanks for the quick fix, really appreciated! 😁
