### ISSUE TITLE
Uncaught Error: Invalid value for "path" argument

### ISSUE THREAD

**Issue by kinsleykajiva** [ItalyPaleAle/svelte-spa-router#167]
I am new to this library so I have tested the setup tutorials but I am facing this error just to run the app with out doing much, so can someone help me out on this as I do not know s what wrong . Below is a sample code of the App.svelte . 

`<script>

    import Router ,{location, link} from 'svelte-spa-router';

	import LeftNav from "./includes/LeftNavigation.svelte" ;
	import HeaderNav from "./includes/HeaderNavigation.svelte";
	import Footer  from "./includes/Footer.svelte";
	import Home  from "./route-pages/HomeDashBoard.svelte";
	import Users  from "./route-pages/Users.svelte";
	import Settings  from "./route-pages/Settings.svelte";

    const routes = {
        '/': Home ,
        'users': Users,
    };

</script>`

Router.svelte:269 Uncaught Error: Invalid value for "path" argument
    at new RouteItem (Router.svelte:269)
    at Router.svelte:381
    at Array.forEach (<anonymous>)
    at instance (Router.svelte:380)
    at init (index.mjs:1471)
    at new Router (Router.svelte:404)
    at create_fragment$7 (Router.svelte:404)
    at init (index.mjs:1486)
    at new App (App.svelte:14)
    at main.js:3

**Comment by ItalyPaleAle** [comment]
Each path defined as string must start with `/`. So `users` needs to be `/users`.

However, I should improve the error message!
