### ISSUE TITLE
Nested routes match wrongfully

### ISSUE THREAD

**Issue by dummdidumm** [ItalyPaleAle/svelte-spa-router#169]
I have a route definition that is only valid inside another route/prefix.

```svelte
<script>
   ...
   const routes = {
     "/*": wrap({
              conditions: [...]
           })
   };
</script>

<Router prefix="/somePrefix" routes={routes} />
```

If I am not on that route but somewhere else (prefix is different), the route is still matched and its conditions are run, in my case causing an endless loop because of some other redirects.

I think the problem lies within [this check](https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Router.svelte#L304): If the route has a prefix that is different, there is no cancellation, instead the matching just continues. I think the code should instead be something like this:

```js
        if (prefix) {
            if (typeof prefix == 'string') {
                if (path.startsWith(prefix)) {
                    path = path.substr(prefix.length) || '/'
                } else {
                    return null;
                }
            }
            else if (prefix instanceof RegExp) {
                const match = path.match(prefix)
                if (match && match[0]) {
                    path = path.substr(match[0].length) || '/'
                } else {
                    return null;
                }
            }
        }
```

**Comment by ItalyPaleAle** [comment]
Oh this is an interesting use case.

When I designed nested routers, I imagined them as being part of another component. For example:

App => Router (1) => Foo => Router (2)
(where Foo is a route on Router (1))

In the case above, Router (2) is not even mounted unless you're inside the Foo route and component.

If I understand correctly, instead, you want Router (2) to be mounted directly inside App and just be inactive unless the prefix is matched? 

If so, I think your example above makes sense and I'd happily accept this if you submitted a PR (so you get credit for the change :) )

**Comment by dummdidumm** [comment]
Actually the flow is as you described, it's App => Router (1) => Foo => Router (2) for me, but when navigating away from Router (2) that sub router is still active and will match stuff unexpectedly. In my case it's logout->redirect to `/login` -> Route (2) matching due to `/*` and doing a redirect on it's own -> Router (1) catching it and redirecting to `/login` because not authenticated -> endless loop.
I'll have a look into making a PR.

**Comment by ItalyPaleAle** [comment]
Ok. I'm not sure I follow your app's structure, but sounds good nevertheless!
