### ISSUE TITLE
Issue with highlighting active path with wildcard 

### ISSUE THREAD

**Issue by mhatvan** [ItalyPaleAle/svelte-spa-router#172]
I want to use this variation of the code below for highlighting nested nav links: 
```<a href="#{link}" use:active={{path: link + '/*', className: 'active', inactiveClassName: 'inactive'}}>Say hi!</a>```

I am iterating over a list of paths and the respective active item gets highlighted correctly when the paths are `/hello`, `/test`. 

Unfortunately, It doesn't work with the `/hello/*`, `/test/*` wildcard variants. All the items are inactive, whenever I click other nav items, all stay inactive, no item becomes active.

**Comment by ItalyPaleAle** [comment]
Thanks for the report. Are you able to share some code sample to reproduce this?

**Comment by mhatvan** [comment]
@ItalyPaleAle Yes, I was able to reproduce it in an isolated Svelte REPL: https://svelte.dev/repl/9d22e449aba84325afec83ab4455c832?version=3.31.0

**Comment by ItalyPaleAle** [comment]
Thanks for sharing that. I think this is actually working as designed.

When you try to match an active link as `/hello/*`, that matches all links that start with `/hello/` **and** have something after that. So, it would match `/hello/world`, but NOT `/hello/` or `/hello`.

In your case, you might want to use a regular expression for matching active links, such as `path: /^\/hello(\/(.*?))?$/` ([test here](https://regex101.com/r/FaMBwY/1))

**Comment by mhatvan** [comment]
Ah, thank you for the explanation!

Its ugly but it works: `new RegExp('^(\\' + navItem.link + ')(/(.*?))?$', 'g')`
