### ISSUE TITLE
Svelte REPL Live/Hot Reload

### ISSUE THREAD

**Issue by rogueyoshi** [ItalyPaleAle/svelte-spa-router#173]
https://svelte.dev/repl/6e7546119cff41fabe35df3ef999ff7e?version=3.29.4

Live/Hot Reload doesn't seem to work correctly on the REPL.

**Comment by ItalyPaleAle** [comment]
What is the issue you're experiencing? It seems to be working fine for me

PS: You should start links with `#/` and not `/#`. So the correct nav should actually be:

```
<a  href="#/">Home</a>
<a href="#/about">About</a>
<a href="#/blog/colors">Colors</a>
```

**Comment by rogueyoshi** [comment]
1. Navigate to About.
2. Attempt editing About.svelte while viewing it.

When you do, it goes back to the Index route, so hot reload only works on the page designated as index at any given time.

**Comment by rogueyoshi** [comment]
I have a separate question. How do I access props from the current route's component?

**Comment by ItalyPaleAle** [comment]
> it goes back to the Index route, so hot reload only works on the page designated as index at any given time

This is an issue with the Svelte REPL and not with the router. Because the REPL is used as a sandbox only, I am not interested in investing lots of energy in quirks specific to the REPL, sorry.

>  How do I access props from the current route's component?

See: https://github.com/ItalyPaleAle/svelte-spa-router#parameters-from-routes
