### ISSUE TITLE
Disable history mode

### ISSUE THREAD

**Issue by dsoloha** [ItalyPaleAle/svelte-spa-router#176]
Is it currently possible to disable history mode with the current version? If not, that might be an idea worth considering, for use cases where users shouldn't be able to navigate back and forth with the browser controls (in a text-based game, for example).

**Comment by ItalyPaleAle** [comment]
Thanks for opening this issue. I think this is out-of-scope of this router: the goal of a client-side router is precisely to support history navigation, persist across page reloads, etc.

If you don't want that, you could just store the current state in a Svelte store and then display a component based on that state

**Comment by dsoloha** [comment]
@ItalyPaleAle Right, that makes sense. If you wouldn't mind, could you give me a quick example of what an implementation of this would look like? Still a bit new to the routing side of things.

**Comment by ItalyPaleAle** [comment]
Sure.

You could do it in many ways, but the simplest I can think of is having a Svelte store called `view` that contains the name of the view you want to load. Your "router" will be a sequence of if's:

```svelte
{#if $view == 'home'}
  <Home />
{:else if $view == 'foo'}
  <Foo />
{/if}
```

And then changing the view just requires setting a new value for the store, such as `$view = 'foo'`

Of course this won't scale when you have lots of views (having dozens of if's doesn't look too good) so you could for example create a function that reads the value of `$view` and returns a Svelte component... Or you can get creative :)

**Comment by dsoloha** [comment]
Thank you, much appreciated.
