### ISSUE TITLE
Failed to load node_modules/svelte-router-spa/src/components/navigate.svelte

### ISSUE THREAD

**Issue by nezlicodes** [ItalyPaleAle/svelte-spa-router#178]
I am having troubles with my build. I keep getting this error message:

```
[snowpack] ! installing dependencies...
[snowpack] Failed to load node_modules/svelte-router-spa/src/components/navigate.svelte
  Try installing rollup-plugin-svelte and adding it to Snowpack (https://www.snowpack.dev/#custom-rollup-plugins)
[snowpack] Install failed.
```

Here is my snowpack.config.js file
```


module.exports = {
  plugins: ['@snowpack/plugin-webpack', '@snowpack/plugin-svelte'],
  installOptions: {
    rollup: { plugins: [require('rollup-plugin-svelte')()] }
  },
  extends: '@snowpack/app-scripts-svelte',
  proxy: {
    '/api': 'http://localhost:3000/api',
  },
  devOptions: {
    out: 'dist/',
    port: 4242,
  },
  buildOptions: {
    baseUrl: 'dist/',
  },
  alias: {
    '@components': './src/components',
    '@state': './src/state',
    '@features': './src/features',
    '@models': './src/models',
    '@themes': './src/themes',
  },
}

```

Am I doing this wrong?
Thanks in advance for your help.

Versions : 
 "rollup-plugin-svelte": "^7.0.0".
  "snowpack": "^2.18.4".
 "svelte-router-spa": "^5.8.3"

**Comment by ItalyPaleAle** [comment]
Sadly looks like you're using a different module. Someone decided to create [svelte-router-spa](https://github.com/jorgegorka/svelte-router) named after this (svelte-spa-router) and the name was bound to create confusion.

**Comment by nezlicodes** [comment]
> 
> 
> Sadly looks like you're using a different module. Someone decided to create [svelte-router-spa](https://github.com/jorgegorka/svelte-router) named after this (svelte-spa-router) and the name was bound to create confusion.

Thank you.
