### ISSUE TITLE
Keep querystring when use pop()

### ISSUE THREAD

**Issue by gryckelynck** [ItalyPaleAle/svelte-spa-router#180]
I generally use the "pop()" function to go back when I don't know what is the previous/source page. But, if I have a page with querystring like: "#/mypage?a=1", the "pop()" function remove URL parameters.
How to keep the query string parameters in this case?
Is there a way to know what is the source page in svelte-spa-router?

**Comment by ItalyPaleAle** [comment]
That shouldn't happen: pop should just send people back to the previous page and preserve the querystring.

Can you share some code to repro the issue?

**Comment by gryckelynck** [comment]
Sorry, there is an error in my test.
Only valid question here is: 
> Is there a way to know what is the source/previous page in svelte-spa-router?

**Comment by ItalyPaleAle** [comment]
There's no API in the router to do that, no. The web platform doesn't include an API for that because that would allow a website to snoop where a user was before.

**Comment by gryckelynck** [comment]
Thank you very much for your answer (and svelte-spa-router).
I understand.
I'd thinking to use store to keep track of previous page when route change.

**Comment by kilianso** [comment]
@ItalyPaleAle I have a question about the exact opposite. I have querystrings like `?chat` in my URL to determine the active tab in an overlay route. Now if use `pop()` to navigate back, the query params persist. That causes, that `use:active` on the previous page doesn't work anymore. Is there a setting in svelte-spa-router to remove all query params when navigating or any other idea on how to approach this?
