### ISSUE TITLE
Transition wrapper for Routes

### ISSUE THREAD

**Issue by joshua1** [ItalyPaleAle/svelte-spa-router#182]
@ItalyPaleAle with respect to page transitions where we have to include transition tags like the below
```
<div transition:fade="{{delay: 250, duration: 300}}">...</div>
```
for all pages/route components becomes cumbersome and repetitive after a while. is it possible to use a wrapper around the routes like this
```
<PageTransition>
     <Router {routes}/>
</PageTransition>
```
this does not work currently with svelte-spa-router.
N.B Thanks for this library

**Comment by ItalyPaleAle** [comment]
Sorry, will not include this to keep the code lightweight. It can be defined in each component as you showed above.
