### ISSUE TITLE
How to open the URL in new tab with push()

### ISSUE THREAD

**Issue by kota-yata** [ItalyPaleAle/svelte-spa-router#186]
Though push method is useful for opening URL from JavaScript, I have no idea how to open the URL in new tab using push method. Is there any means to do this?

**Comment by kota-yata** [comment]
The simplest solution is ```window.open("#/somepage");```, but I feel like this is a forcible solution. I hope there is better method...

**Comment by ItalyPaleAle** [comment]
This is not possible with this router not really in scope, as when you use multiple tabs you don't have a SPA (Single Page App) anymore.

It's not to say that you can't use the router within the new tab. But opening new tabs or simply navigating to a different URL is not something a router can help with.
