### ISSUE TITLE
use:active misses updates to href

### ISSUE THREAD

**Issue by iffy** [ItalyPaleAle/svelte-spa-router#187]
Thank you for making this router!

With a link like this, the `active` class isn't applied when `$somevalue` changes.

```js
<a use:active href="#{$somevalue}/something">Something</a>
```

Here's a REPL with instructions for seeing the problem:

https://svelte.dev/repl/cd55001f50c34672a5e972ef1b5eda0e?version=3.31.2

**Comment by iffy** [comment]
FWIW, here's my workaround replacement for `use:active`. It doesn't have as many features as the one from svelte-spa-router, and I don't know how bad the performance is for using a MutationObserver, but it works for my use case:

```js
export default function active(node) {
  function gethref() {
    let href = node.getAttribute('href');
    if (href.startsWith('#')) {
      href = href.substr(1);
    }
    return href;
  }
  function update() {
    let href = gethref();
    if (window.location.hash.substr(1) === href) {
      node.classList.add('active');
    } else {
      node.classList.remove('active');
    }
  }
  let observer = new MutationObserver((mutationList) => {
    update();
  })
  observer.observe(node, {
    attributes: true,
    attributeFilter: ["href"],
  })
  let unsub = location.subscribe(newlocation => {
    update();
  })
  return {
    destroy() {
      unsub();
      observer.disconnect();
    }
  }
}
```

**Comment by ItalyPaleAle** [comment]
This is by design because when you pass no option to `use:active`, it picks up the element's href, and then it has no way to know if it's updated.

Without observers, this should be possible if you pass a value to `use:active={{path: $somevalue + '/something'}}`
