### ISSUE TITLE
Add a before loading event

### ISSUE THREAD

**Issue by Vaxarm** [ItalyPaleAle/svelte-spa-router#188]
Hi,

Would it be possible to add an event before any route action. 
Whether it will be successful or not.

I would like to be able to modify the route before loading it.
For example, I need to change link before any navigation in '/:link?/my/route'.

At the moment we only have an event when a route is successfully loaded.
We don't have any event when the route is not recognized.

What do you think ?

**Comment by weeblr** [comment]
Hi

I'd like to second that, although for a different purpose. I'd like to be able to prevent any route action to happen.

The use case is running a svelte app inside of another app or site. Typically in my case, a WordPress or Joomla extension or theme. 

However the parent CMS have links that may use hashes as well, such as href='#'. I namespaced my routes to avoid conflict but I cannot prevent the router to load a route.

If I use a guard and return false when not one my routes, the router does not load any  route at all, so I end up with a blank screen.

Either a guard could be made to return true, false or 'cancel' to do absolute nothing.

Or maybe a separate event beforeLoading as suggested above?

Thanks for any pointer, this is kinda of a big deal if I cannot work around this.

**Comment by weeblr** [comment]
@Vaxarm You may be able to achieve what you want by using a route guard that files on some condition. When the condition fails, the router triggers the conditionsFailed event and there you can change the URL ([see this page](https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#route-wrapping).

**Comment by Vaxarm** [comment]
@weeblr Thanks, I think I already tried this solution with no luck.
But I will give it another shot in the meantime.

Yes, it's a big deal on my side too, I really need to be able to listen at any router event, even if it's not successful.

**Comment by weeblr** [comment]
@Vaxarm let us know if you can use this solution, I have not tried it myself. 

To solve my issue, I'm now running a forked version, could not find any other way.

**Comment by ItalyPaleAle** [comment]
Events are mostly used for notifications. In your case, have you taken a look at route pre-conditions? https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#route-pre-conditions

Inside that, you can safely call `replace` or `push` to change the route.

**Comment by weeblr** [comment]
@ItalyPaleAle I will open a separate issue then, using guard does not solve trying to use the router inside of WordPress or Joomla.
