### ISSUE TITLE
Why the query string API is different with param's ?

### ISSUE THREAD

**Issue by donnisnoni** [ItalyPaleAle/svelte-spa-router#189]
Thank's for this nice simple router lib for svelte!

BTW I just curious why the query string API is different with param's? Reason's behind that maybe?

**Comment by ItalyPaleAle** [comment]
You're welcome!

Do you mind giving me an example of what's different?

**Comment by donnisnoni** [comment]
Ahh... sorry I found the answer on the readme. I forgot to close this. Will close this now 😁
