### ISSUE TITLE
Injecting props into components

### ISSUE THREAD

**Issue by pr0mixe** [ItalyPaleAle/svelte-spa-router#19]
Hello, is there a way to injects props into components being routed to? Some of my components depend on props to be mounted with. I know I could pass simple things as params in a route, but some of the props I use are web workers or complex objects. How would I go about injecting them into components mounted upon navigating to a route? Thanks!

**Comment by ItalyPaleAle** [comment]
I feel like I might be missing some context (feel free to provide an example), but would you be able to add those components requiring props as sub-components? (I.e. Child components of the route)

**Comment by pr0mixe** [comment]
In my App.svelte where I put the `<Router {routes}/>` I also instantiate some web workers that are global to entire app. Before adding the router I used to inject these web workers as props into child components of App.svelte, i.e.: `<ProjectManager {mySocket} {webWorkerDatabase}/>` . 
Now, with the router I want to make a route: `const routes = '/': ProjectManager }`. But I'd like to pass mySocket and webWorkerDatabase to that ProjectManager component when the user goes to '/' route. Otherwise I have to instantiate brand new webWorkerDatabase inside ProjectManager (and subsequently in other child components separately) which would be undesirable. As opposed to instantiating these web workers once in App.svelte and passing them into child components. I hope you get the picture. Any suggestions? Thank you!

**Comment by ItalyPaleAle** [comment]
Since they’re part of the global state, I’d store them in a module:

````js

// file: workers.js
export let myworker = nil

// file: main.js
import {myworker} from 'workers.js'
// then, in the init function, set it to something:
myworker = ....

// component: MyRoute.svelte
import {myworker} from 'workers.js'
// do whatever you need with myworker
````

**Comment by pr0mixe** [comment]
Thank you, this approach works. )

**Comment by sevaho** [comment]
hi @ItalyPaleAle I don't get it. I'm getting this error:

```
main.js:8 Uncaught ReferenceError: myworker$1 is not defined
```

this is my main.js file:

```
import App from "./App.svelte";
import {myworker} from "./wokrer.js";

const app = new App({
  target: document.body,
  props: {},
  myworker: myworker
});

export default app;
```

**Comment by ItalyPaleAle** [comment]
You should pass myworker inside props if you want it to be a prop.

**Comment by beinoriusju** [comment]
Another way to pass in props would be `routeLoaded` event. Unfortunately `event.detail.component` **references component`s name and not component itself**. That's greatly limits my choices.

Can you give me an argument for this decision?

https://github.com/ItalyPaleAle/svelte-spa-router/blob/943c339dc9a841ecbc3e2b9a6501ab80142ff263/Router.svelte#L311
