### ISSUE TITLE
routeLoaded event details missing route params

### ISSUE THREAD

**Issue by spooky** [ItalyPaleAle/svelte-spa-router#190]
This is a feature request.
The router provides the nice `params` object with values resolved from the route template.
That object would come in handy as one of the event detail fields for the routeLoaded event (routeLoading as well if that's possible).

**Comment by ItalyPaleAle** [comment]
It might be doable. The `params` object would be read-write, so users (devs) could modify the state of the app from that. Which might or might not be desirable.

What is your use case?

**Comment by spooky** [comment]
Not a very critical one - setting page title based on route and it's params ;)

**Comment by ItalyPaleAle** [comment]
Why not doing that in the component itself?

**Comment by spooky** [comment]
I am, but I'd rather have it in the router.

**Comment by JestDotty** [comment]
I'm trying to figure out page breadcrumbs right now and this feature would make it possible I think

**Comment by ItalyPaleAle** [comment]
Fixed in the master branch
