### ISSUE TITLE
Hello!When I use the route transition animation, I encounter a very distressed problem

### ISSUE THREAD

**Issue by dbMongola** [ItalyPaleAle/svelte-spa-router#194]
I'm very sorry to use Baidu translation to translate this problem, I'm really sorry, I admit that my English is very poor,but I want to get a good solution.
The problem is this.
If a page is animated, for example
```html
// page1
<div in:fly={{ x: -1000 }} out:fly={{ delay: 2000, x: 1000}} >
Page1 Content
</div>

// page2
<div in:fly={{ x: -1000 }} out:fly={{ delay: 2000, x: 1000}} >
Page2 Content
</div>
```

When you switch routes, you will find that the last page is delayed to unload due to delay, but at the same time, the new page has been loaded and displayed on the page.
So, when the height of the previous page exceeds the height of the window, you will find that the new page has been loaded and exists at the end of the previous page, and the animation of the new page has been executed, but you can't see the animation.

**Comment by dbMongola** [comment]
So, can the new page be loaded after the last page animation

**Comment by sserdyuk** [comment]
This is a generic issue with transitioning two blocks of content. Here's an example https://svelte.dev/repl/f78d729b00c14328af52a180249417c3?version=3.32.3

The "solution" to the problem is to remove the "out" animation (just like the svelte-spa-router documentation has it). This way the "away" content in removed instantly and the "to" content is animated. This works well enough with "fade" animation. If you want to keep using the "out" and "fly" animations, you will need to have both pages designed with "position: absolute", so they can coexist without breaking apart the layout of the page. Here's an example of how it can be done https://svelte.dev/repl/9dd1c9eb601644f4926f73c77ea145f9?version=3.32.3

**Comment by dbMongola** [comment]
> This is a generic issue with transitioning two blocks of content. Here's an example https://svelte.dev/repl/f78d729b00c14328af52a180249417c3?version=3.32.3
> 
> The "solution" to the problem is to remove the "out" animation (just like the svelte-spa-router documentation has it). This way the "away" content in removed instantly and the "to" content is animated. This works well enough with "fade" animation. If you want to keep using the "out" and "fly" animations, you will need to have both pages designed with "position: absolute", so they can coexist without breaking apart the layout of the page. Here's an example of how it can be done https://svelte.dev/repl/9dd1c9eb601644f4926f73c77ea145f9?version=3.32.3

**Comment by dbMongola** [comment]
> 这是转换两个内容块的普遍问题。这是一个示例https://svelte.dev/repl/f78d729b00c14328af52a180249417c3?version=3.32.3
> 
> 该问题的“解决方案”是删除“输出”动画（就像svelte-spa-router文档中那样）。这样，立即删除了“离开”的内容，并对“到达”内容进行了动画处理。这对于“淡入淡出”动画效果很好。如果要继续使用“ out”和“ fly”动画，则需要将两个页面都设计为带有“ position：absolute”，这样它们可以共存而不会破坏页面的布局。这是一个如何完成的示例https://svelte.dev/repl/9dd1c9eb601644f4926f73c77ea145f9?version=3.32.3

Yeah，It's a good idea, but I've shortened the execution time of the out so that I can finish the out animation before the next entry animation starts

**Comment by dbMongola** [comment]
> This is a generic issue with transitioning two blocks of content. Here's an example https://svelte.dev/repl/f78d729b00c14328af52a180249417c3?version=3.32.3
> 
> The "solution" to the problem is to remove the "out" animation (just like the svelte-spa-router documentation has it). This way the "away" content in removed instantly and the "to" content is animated. This works well enough with "fade" animation. If you want to keep using the "out" and "fly" animations, you will need to have both pages designed with "position: absolute", so they can coexist without breaking apart the layout of the page. Here's an example of how it can be done https://svelte.dev/repl/9dd1c9eb601644f4926f73c77ea145f9?version=3.32.3

Yeah，It's a good idea, but I've shortened the execution time of the out so that I can finish the out animation before the next entry animation starts
