### ISSUE TITLE
Use URLSearchParams in the docs

### ISSUE THREAD

**Issue by PierBover** [ItalyPaleAle/svelte-spa-router#195]
Instead of recommending to use `qs` most browsers include `URLSearchParams` to parse query strings:

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

Would you accept a PR to change the docs?

**Comment by ItalyPaleAle** [comment]
Oh good catch. Sure feel free to submit one, thanks!

**Comment by PierBover** [comment]
Done: https://github.com/ItalyPaleAle/svelte-spa-router/pull/198
