### ISSUE TITLE
Is there a way to change the hash in the URL without triggering a page change?

### ISSUE THREAD

**Issue by PierBover** [ItalyPaleAle/svelte-spa-router#196]
I'm guessing the router is listening to hash changes and this is not possible though.

I have a modal that opens an image and the client wants for users to be able to share URLs that will open that precise modal.

Eg: `#/images?id=12345`

This works fine. The problem is that when trying to remove the query string by doing `window.location.hash = '#/images';` when closing the modal, will reload the `/images` route.

I haven't tried it, but I imagine the problem will be the same when trying to add a query string directly (not using a link).

Edit:

I've tried solving this with route guards, thinking I could prevent a route change if the current route was `/images` and the next route was `/images`. Unfortunately there is no way to know which was the current route when the route change was triggered.

```js
conditions: [
	(detail) => {
		console.log(get(location)); // returns /images even when coming from a different route
		console.log(detail); // detail does not include the previous route
		if (detail.location === '/images') return false;
		return true;
	}
]
```

It's a bit weird `location` includes the next route before the transition has happened, although I understand changing this behavior could break apps using this router.

Would you accept a PR to add the previous route in the `detail` object?

**Comment by ItalyPaleAle** [comment]
`location` includes the route that is being loaded.

I can accept a PR, but we need to be mindful of the fact that this would keep the state in memory and so would not survive page reloads. I am not sure if this could damage the developer/user experience.

**Comment by PierBover** [comment]
After a couple of hours I'm giving up.

The implementation was simple, but I'm not able to get the tests running.

You can see the changes I made here: https://github.com/PierBover/svelte-spa-router/tree/detail-lastLocation

If anyone wants to use my fork with the `detail.lastLocation` feature:

```
npm install git://github.com/PierBover/svelte-spa-router.git#detail-lastLocation 
```

**Comment by NfNitLoop** [comment]
FWIW: I'm running into this too.   I'm trying to implement infinite scroll on one of my pages, and keep rough scroll position in URLs with `#/myPage?offset=$someOffset`. 

However, any time I update `window.location.hash`, even though I can see that the `$location` doesn't change, it always forces a reload of the (SPA) page.

**Comment by PierBover** [comment]
@NfNitLoop I ended up [implementing my own router](https://github.com/PierBover/roots-svelte-router#query-string-parameters) which allows you change the query params without a route change. It's still in alpha though but there are no major bugs that I'm aware of.
