### ISSUE TITLE
Nested Routes Feature Not Working Properly

### ISSUE THREAD

**Issue by martinsodabi** [ItalyPaleAle/svelte-spa-router#20]
I am trying to use the nested routes feature as shown in the advanced usage section of the GitHub, but it is not working as expected.

**Comment by ItalyPaleAle** [comment]
@martinsodabi Can you please provide some context and code sample?

**Comment by martinsodabi** [comment]
`
<script>
  import Router from "svelte-spa-router";
  import { routes } from "../DashBoardRoutes.svelte";
</script>

<h1>DashBoard</h1>
<Router {routes} />


<script context="module">
  import MyShifts from "./dashboard/MyShifts.svelte";

  export const routes = {
    "/dashboard/:myshifts": MyShifts
  };
</script>



<script context="module">
  import Home from "./Home.svelte";
  import SignUp from "./account/SignUp.svelte";
  import LogIn from "./account/LogIn.svelte";
  import ForgotPassword from "./account/ForgotPassword.svelte";
  import RecoverAccount from "./account/RecoverAccount.svelte";
  import VerifyAccount from "./account/VerifyAccount.svelte";
  import DashBoard from "./dashboard/DashBoard.svelte";
  import NotFound from "./NotFound.svelte";

  export const routes = {
    "/": Home,
    "/login": LogIn,
    "/signup": SignUp,
    "/verifyaccount": VerifyAccount,
    "/forgotpassword": ForgotPassword,
    "/recoveraccount": RecoverAccount,
    "/dashboard/*": DashBoard,
    "*": NotFound
  };
</script>



<script>
  import Router from "svelte-spa-router";
  import { routes } from "./Routes.svelte";
  import Header from "./Header.svelte";
</script>

<style>

</style>

<main>
  <Header />
  <Router {routes} />
</main>
`

**Comment by martinsodabi** [comment]
`<script>
  import Router from "svelte-spa-router";
  import { routes } from "./Routes.svelte";
  import Header from "./Header.svelte";
</script>

<style>

</style>

<main>
  <Header />
  <Router {routes} />
</main>`

**Comment by martinsodabi** [comment]
```
<!-- App.svelte -->
<script>
  import Router from "svelte-spa-router";
  import { routes } from "./Routes.svelte";
  import Header from "./Header.svelte";
</script>

<style>

</style>

<main>
  <Header />
  <Router {routes} />
</main>


<!-- Routes.svelte -->
<script context="module">
  import Home from "./Home.svelte";
  import SignUp from "./account/SignUp.svelte";
  import LogIn from "./account/LogIn.svelte";
  import ForgotPassword from "./account/ForgotPassword.svelte";
  import RecoverAccount from "./account/RecoverAccount.svelte";
  import VerifyAccount from "./account/VerifyAccount.svelte";
  import DashBoard from "./dashboard/DashBoard.svelte";
  import NotFound from "./NotFound.svelte";

  export const routes = {
    "/": Home,
    "/login": LogIn,
    "/signup": SignUp,
    "/verifyaccount": VerifyAccount,
    "/forgotpassword": ForgotPassword,
    "/recoveraccount": RecoverAccount,
    "/dashboard/*": DashBoard,
    "*": NotFound
  };
</script>


<!-- DashBoardRoutes.svelte -->
<script context="module">
  import MyShifts from "./dashboard/MyShifts.svelte";

  export const routes = {
    "/dashboard/:myshifts": MyShifts
  };
</script>


<!-- DashBoard.svelte -->
<script>
  import Router from "svelte-spa-router";
  import { routes } from "../DashBoardRoutes.svelte";
</script>

<h1>DashBoard</h1>
<Router {routes} />
```

**Comment by martinsodabi** [comment]
When I navigate to "/dashboard/" I get my DashBoard component showing up, but when I enter any string in "/dashboard/example" I get DashBoard and MyShift component showing up, "/dashboard/:example" is not in my routes.

**Comment by ItalyPaleAle** [comment]
Got it. It's because of this line:

````
"/dashboard/:myshifts": MyShifts
````

The router uses [regexparam](https://github.com/lukeed/regexparam) (the only dependency) to parse that string. In regexparam, `:` in front of a path component means that it's a named parameter, essentially a variable.

This means that `/dashboard/:myshifts` will match `/dashboard/` followed by anything, and store the path component in the `myshift` parameter.

If you want to match `/dashboard/myshifts` only, you need to replace that line with:

````
"/dashboard/myshifts": MyShifts
````

This happens both in nested routers and in top-level ones.

**Comment by abezulski** [comment]
@ItalyPaleAle 
I know this is closed and well explained but I had the very same issue with nested routes (I followed your example for nested routing in Advanced section):

```
// main routes
const routes = {
    '/': Home,
    '/listings': Listings,
    '/listings/*': Listings,
    '*': Home
};

//nested routes
const prefix = '/listings';
const routes = {
    '/:category': ListView
};
```

When navigating between categories it was fine (like /#/listings/active or /#/listings/expired) but navigating to main one (/#/listings) and back to any category would result in weird behaviour - same component/page appearing multiple times. From the functionality point of view, those views are the same - only data is different.

I eventually gave up on idea of nested routes and moved to the root one with optional parameter:
```
const routes = {
    '/': Home,
    '/listings/:category?': Listings,
    '*': Home
};
```

**Comment by ItalyPaleAle** [comment]
@abezulski This is odd. Do you by any chance use any transition? I wonder if that's connected to #241 which is actually an issue upstream in the Svelte compiler

**Comment by abezulski** [comment]
@ItalyPaleAle Damn, this is what I was also seeing: https://github.com/ItalyPaleAle/svelte-spa-router/issues/241#issuecomment-928221452

I have transition only on the Home page, but I am also using store that changes between navigation. I will reply in #241, thanks for your reply!

**Comment by algaly** [comment]
Try **replacing** your **a tag** with **button** and use the **push** method.
Worked for me! (even with animation)
