### ISSUE TITLE
Hide/Show routes, do not destroy them; a built-in feature?

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#200]
I've been using this router for a while now. It's amazing. Thanks again.

But I have found that I often need not to destroy the contents of a route; I just need to hide it and show another one.

This is the famous case of "list/detail"; to be clear the classic Gmail example:

1. email list
1. I click on an email
1. the email list is hidden (NOT destroyed)
1. the chosen email is displayed
1. if I go back, the chosen email is destroyed and the list reappears (without being recreated from scratch)

Now I'm using a lot of code and css classes.

What do you think about making this a feature built into the router?

**Comment by ItalyPaleAle** [comment]
Currently, the unloaded component is destroyed (ie. removed from the DOM). Maintaining that would likely be a major architectural change in the router, and might not work for everyone (memory consumption would certainly balloon). Sorry :( But happy to accept a PR if you want!

**Comment by frederikhors** [comment]
Ok. I understand you don't want to put this feature in now.

But can you at least tell me if what I say makes sense?

In a classic `list > detail` example, does it make sense to avoid dostroying every time you go back and forth?

**Comment by frederikhors** [comment]
I mean from a performance (rendering speed) point of view.

**Comment by frederikhors** [comment]
I have already tested and on all devices (from the slowest to the fastest): the gain in "viewing" speed (in `list > detail`) is impressive.

I am already caching data in memory and localstorage, so there is no roundtrip for the data, I'm just talking about `display: none` / `display: block` behavior.

> but there's also an overhead in keeping more data in the DOM (even if hidden)

And of course I understand what you say about this, but then everyone would use it where they want: I would only use it in "sub-applications". Example:

`Routes: HOME | PLAYERS_LIST | PLAYER_DETAIL`

1. From HOME -> to PLAYERS_LIST: destroying HOME... mounting PLAYERS_LIST -> OK!

1. From PLAYERS_LIST -> to PLAYER_DETAIL: `display: none` PLAYERS_LIST... mounting PLAYER_DETAIL -> OK!

1. From PLAYER_DETAIL -> to PLAYERS_LIST: destroying PLAYER_DETAIL... `display: block` PLAYERS_LIST -> OK! Super fast!.

1. From PLAYERS_LIST -> back to HOME: destroying PLAYERS_LIST... mounting HOME -> OK!

Is my idea clearer now?

Now it can be done, of course, but every time you have to write code that complicates things. Integrating this functionality into the router you are using every day would make it easier.

Anyway thanks again for everything you have done so far!

**Comment by aral** [comment]
@frederikhors Did you end up implementing this feature for yourself, by chance. I just hit it while porting my app from my homespun router to svelte-spa-router. My assumption would have been that routes are cached when created so that going back to them is a simple show/hide for performance reasons.

If you haven’t had a chance, I might look into it. Thanks :)

**Comment by frederikhors** [comment]
Yeah. I do not remember the code but I did it manually. This great router doesn't handle it natively.
