### ISSUE TITLE
the last version of regexparam is 1.2.2           

### ISSUE THREAD

**Issue by yinsang** [ItalyPaleAle/svelte-spa-router#203]
But, this library needs 1.3.0?

**Comment by vladshcherbin** [comment]
![image](https://user-images.githubusercontent.com/6711845/109616801-a7ea2800-7b46-11eb-9b77-f5fbbdc8ae8e.png)

Last one is 1.3.0 😉

**Comment by yinsang** [comment]
Sorry, our company's private NPM registry need to sync the package to 1.3.0.

**Comment by ItalyPaleAle** [comment]
You can certainly use 1.2.2 if that's your only option. Make sure you downgrade the version in the package.json file. It should work without problems.

**Comment by yinsang** [comment]
> You can certainly use 1.2.2 if that's your only option. Make sure you downgrade the version in the package.json file. It should work without problems.

Thanks
