### ISSUE TITLE
Change component for the same path depending on current app state

### ISSUE THREAD

**Issue by tandu** [ItalyPaleAle/svelte-spa-router#206]
For example here are 2 screens: home and login. Home is only available for logged users. I would like to show either Login or Home for '/' path depending on `$auth` state.
```ts
export const routes = derived(auth, $auth => ({
  '/': wrap({
    component: $auth ? HomeScreen : LoginScreen
  })
}))
```
How to force it to update component whenever `auth` state is changed? In my example above it selects correct component only once on routes initialization and if I logout / login later component is not switched to Login / Home.

**Comment by ItalyPaleAle** [comment]
You should use a route pre-condition for that: define the route for logged in users, then in the pre-condition check if the user isn't logged in and send them to the login page. https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#route-pre-conditions

**Comment by tandu** [comment]
thank you, did it that way:

```ts
export const routes = {
  '/': wrap({
    component: HomeScreen,
    conditions: [
      async () => new Promise(resolve => // navigate to login screen if not logged
        auth.subscribe($auth => { $auth ? resolve(true) : replace('/login'), resolve(false) })
      )
    ]
  }),
  '/login': LoginScreen
}
```
