### ISSUE TITLE
userData

### ISSUE THREAD

**Issue by giosifelis** [ItalyPaleAle/svelte-spa-router#208]
This is more of a question than an issue. 

First of all, congratulations on your great router.  It is very well written.  

Just one question, how to I access the userData in a nested route?  I've used the wrap functionality but I cannot figure out how to access the userData in the child route.  

for example i have the following routes:

Parent Route:  Product
     nested route:  product/maininfo
     nested route: product/tags

When the Product route loads I do a server call and I bring the product data which i pass to the userData with wrap
I am trying to access the product data inside the maininfo and tags component which are loaded when the nested routes are loaded

how do i do this?

I would appreciate an example as I have read the documentation but i cannot figure it out.
Thank you

**Comment by anilbhattaraitoronto** [comment]
It looks like your problem can be solved if you make use of svelte/store (writable). That's the way I do in my app for fetching blogs from remote api.
I first push them to the store and make use of the store in the components where I need the blogs.
