### ISSUE TITLE
How to guard route with condition when checking user returns a promise

### ISSUE THREAD

**Issue by robhicks** [ItalyPaleAle/svelte-spa-router#209]
The docs state that condition functions are useful for checking if a user is authenticated and functions must return a boolean. 

How does one check if a user is authenticated with a function that returns a promise and guard the route with a condition?

**Comment by moalamri** [comment]
Have you checked the async pre-conditions example in docs?

**Comment by ItalyPaleAle** [comment]
Route pre-condition handlers can be async function (or just return promises). So you can do async processing in there, just make sure you return a promise that resolves with a boolean true/false!
