### ISSUE TITLE
preload routes

### ISSUE THREAD

**Issue by Kapsonfire-DE** [ItalyPaleAle/svelte-spa-router#210]
I use async routes and I'd like to preload the next routes so it can be displayed instantly

**Comment by frederikhors** [comment]
This is something we may not have yet, @ItalyPaleAle, right?

I'm interested too!

**Comment by Kapsonfire-DE** [comment]
It seems it can be accomplished calling the route.component manually
`    import routes from "./routes";
    import {push} from "svelte-spa-router";
    routes["/Loader"].component().then(() => push('/Loader'));`

**Comment by Kapsonfire-DE** [comment]
Its even possible to preload assets of a route

`
    import {push} from "svelte-spa-router";
    routes["/Loader"].component().then(c => c.default.prototype.preload()).then(() => {
        push('/Loader');
    });`

to be honest, its not very clean.... My suggest would be maybe to extend the routes code
    routes["/Loader"].preload()
    
    Step 1: Loading the Route
    Step 2: Check if Route is exporting a preload function, if exists call it
    Step 3: Resolve

**Comment by Kapsonfire-DE** [comment]
https://github.com/ItalyPaleAle/svelte-spa-router/pull/211

**Comment by ItalyPaleAle** [comment]
If you call `import()` twice with the same file, it will be loaded from the cache. So, if you want to preload a module, just call `import()` in your code when you want to preload it. When the same import is invoked by the router, it will just load the pre-loaded code.

If you want to be fancy, you can also pass your custom logic to `asyncComponent`: as long as it is a Promise that resolves with an imported module, it works.

No need to make changes to the router itself :)
