### ISSUE TITLE
TypeError: Cannot read property 'c' of undefined when push() or replace()

### ISSUE THREAD

**Issue by Trystan-SA** [ItalyPaleAle/svelte-spa-router#212]
When I use the push("/page1")  or replace("/page2") methods, I'm getting an error :

```
Uncaught (in promise) TypeError: Cannot read property 'c' of undefined
    at transition_out2 (main.js:7581)
```

The code that trigger the error :
```
function transition_out2(block, local, detach3, callback) {
    if (block && block.o) {
      if (outroing2.has(block))
        return;
      outroing2.add(block);
      outros2.c.push(() => {      <---- this
        outroing2.delete(block);
        if (callback) {
          if (detach3)
            block.d(1);
          callback();
        }
      });
      block.o(local);
    }
  }
```
(The number "2" that follow each methods names is because of my bundler (esbuild))

It seems to be related to this svelte issue : https://github.com/sveltejs/svelte/issues/3165

The error doesn't trigger when I'm loading my application directly with the URL  "/page1" or "/page2". It only happen when I'm using push() or replace()  (or maybe other methods like pop().)

I don't know if this issue is related to svelte-spa-router or svelte directly. Does svelte-spa-router use transitions ? 

Anyway, I fixed it by changing the line that trigger the error by : 
```
outros2?.c?.push(()=>{
```

And it work well. It sounds like an issue that involve svelte reactivity.

**Comment by ItalyPaleAle** [comment]
What's the code that triggers the error?

No the router doesn't implement transitions in any way. But you can use Svelte transitions if you wish to.

**Comment by ItalyPaleAle** [comment]
Seems to be an upstream error.
