### ISSUE TITLE
Error: Function called outside component initialization using Vite

### ISSUE THREAD

**Issue by Himujjal** [ItalyPaleAle/svelte-spa-router#216]
To reproduce the error, here's the repo: https://github.com/Himujjal/svelte-template-ts/tree/router (NOTE: branch is router).

I am trying to use the router as mentioned in the README.md but I am unable to do so with Vite. I searched for the error in other github issues, but unfortunately, most of them link to either Svelte being a dependency or something related to Sapper. I am although using a purely SPA CSR app.

**Comment by baileyherbert** [comment]
Hey! I'm the creator of the template you're using. Coincidentally we both ran into the same issue at the same time! 😄 

I started a new project with the template and was getting this error. The strange thing is that I have a previous project with the same template that works perfectly. After some debugging, I've tracked the issue down to a bug between Svelte and Vite 2.

The "fix" is to manually trigger the svelte internals to be chunked by vite. This is easy, just import the `svelte` package from within your `App.svelte`:

```ts
import 'svelte';

import Router from 'svelte-spa-router'
import Home from './Home.svelte';
import Profile from './Profile.svelte';
```

If that doesn't fix it immediately, you might need to delete the `node_modules/.vite` directory and then restart the development server.

**Comment by baileyherbert** [comment]
By the way, I edited my initial reply. Looks like a generic `import 'svelte'` caused the Svelte VSCode extension to get upset. Use an empty named import instead if you have trouble. It has the same effect:

```ts
import {} from 'svelte';
```

**Comment by Himujjal** [comment]
@baileyherbert yeah. i asked for this template on reddit not a long time ago. And I did find that the issue is related to Vite 2. I think this issue is being tracked in the Sveltekit repo too.

BTW. I went with rollup. Vite 2 was giving me a few troubles.
