### ISSUE TITLE
Route with two params emptied when refresh hit.

### ISSUE THREAD

**Issue by michaelcuneo** [ItalyPaleAle/svelte-spa-router#218]
I've got an SPA Router project set up where I have two parameters being sent to a route.

The route loads up first time perfectly, the param is used to obtain data from a store, and change some conditionals to suit the rendering of the page.

If someone hits refresh (Because I never know what people are doing with my app), even though refresh isn't neccessary to be pushed... if it is, for whatever reason, the page breaks.

When refresh is hit, the page params are nulled. But the address bar still states the correct params, and the processing on the params on the page are still the same... 

Any idea where it's stuffing up?

```
  import { posts } from '../utils/store.js';

	$: post = getPost(params.id, $posts) || [];
	$: mode = params.mode;
	let title = '';

	const getPost = (nameKey, myArray) => {
    for (var i=0; i < myArray.length; i++) {
      if (myArray[i].id === nameKey) {
        return myArray[i];
      }
    }
	}

// at this point... post, mode and title, are correct filled with data.
// but a refresh destroys post, mode and title.

	const handleEdit = () => {
		if (mode ==='display') {
			mode = 'edit';
		} else {
			mode = 'display';
		};
	};
	const handleSave = () => console.log("Saving");

	export let params = [];
``` 

My routes are 

```
'/post/:mode/': PostAdmin, // When adding a post.
'/post/:mode/:id': PostAdmin, // When Editing a post.
```

**Comment by ItalyPaleAle** [comment]
Have you solved this? I'm afraid I don't have enough context to understand what's broken, I'd need to see a "MVP" that can replicate this issue..

**Comment by michaelcuneo** [comment]
I found the issue eventually, I realised that the routes even though initially set, don't reload on refresh unless pushed into a onMount and onUpdate I think. I also had to persist the state and solved it like this...
