### ISSUE TITLE
Information on previous route in routeLoading and routeLoaded events

### ISSUE THREAD

**Issue by TheMaikXX** [ItalyPaleAle/svelte-spa-router#219]
Hello,
Just a quick idea: Could this be part of an svelte-spa-router API? Although I can imagine it would be a breaking change.
Now I have to create stores for holding current and previous routes by myself in many applications.

Thanks for the router, the only thing I missed in Svelte :)

**Comment by ItalyPaleAle** [comment]
Thanks for the suggestion.

I think I will pass on this however, as it would introduce a lot of complexity. First, there's the fact that the router needs to keep in memory all the previous states, which is not always practical. Then, after this is implemented, we would need to find a way to persist the state across page refreshes (so probably using localStorage), and possibly across tabs too.

I think apps that need this are best implementing it in their own code.
