### ISSUE TITLE
Router component has no cleanup during unmount

### ISSUE THREAD

**Issue by DimitrisRK** [ItalyPaleAle/svelte-spa-router#222]
There will be cases that one will need to toggle `Router` visibility, mount/unmount it in short, using a condition.
During unmount, component does not cleanup old window events and `loc` store does not unsubscribe resulting in multiple store subscriptions.

I tend to unmount `Router` in some cases, therefore I'm experiencing memory leaks and duplicate functionality like calling route preconditions multiple times and so on. This is a bit annoying.

**Comment by ItalyPaleAle** [comment]
Fixed by #221 Thanks for the PR
