### ISSUE TITLE
Plugin lacks transpile on install

### ISSUE THREAD

**Issue by DimitrisRK** [ItalyPaleAle/svelte-spa-router#230]
Many modules nowadays are installed and get transpiled so that developers have no issues like ES6 support.
For instance, svelte and few other packages have the following format inside package.json:
```
{
  "name": "svelte",
  "version": "3.38.2",
  "description": "Cybernetically enhanced web apps",
  "module": "index.mjs",
  "main": "index",
```
svelte-i18n:
```
{
  "name": "svelte-i18n",
  "version": "3.3.9",
  "main": "dist/runtime.cjs.js",
  "module": "dist/runtime.esm.js",
  "types": "types/runtime/index.d.ts",
  "bin": {
    "svelte-i18n": "dist/cli.js"
  },
```
svelte-toast
```
{
  "name": "@zerodevx/svelte-toast",
  "version": "0.3.0",
  "description": "Simple elegant toast notifications",
  "author": "Jason Lee <jason@zerodevx.com>",
  "svelte": "src/index.js",
  "module": "dist/index.mjs",
  "main": "dist/index.js",
```
As you can see, they provide compiled `main` and `module` versions.

I personally have problems with this specific plugin when testing with mocha. I use babel to transpile my source code, but I would like to avoid transpiling node_modules.

**Comment by ItalyPaleAle** [comment]
What is the problem you're experiencing with mocha?

From the very beginning, this package has never published compiled files, but only the raw `.svelte` files:

https://github.com/ItalyPaleAle/svelte-spa-router/blob/f0f38429b0c2f330101036375a8bffb6e8180a7d/package.json#L5-L7

This was done so users could just do `import Router from 'svelte-spa-router'` in a Svelte file and it would work regardless of modules, transpilers, etc... It will go through the Svelte compiler like every other Svelte file.

**Comment by DimitrisRK** [comment]
@ItalyPaleAle I have issues with active.js and wrap.js.
JavaScript files aren't compiled from svelte compiler, so Mocha complains about import and export keywords.

**Comment by ItalyPaleAle** [comment]
No, JS files are meant to be compiled by the Svelte compiler too. As long as everything goes through the Svelte compiler (and associated tooling), it should work.

You can see we are using mocha for tests in this repo too. The important thing is that mocha should run tests against the compiled files and not the source.

**Comment by DimitrisRK** [comment]
> No, JS files are meant to be compiled by the Svelte compiler too. As long as everything goes through the Svelte compiler (and associated tooling), it should work.
> 
> You can see we are using mocha for tests in this repo too. The important thing is that mocha should run tests against the compiled files and not the source.

The thing is we use a certain test environment with coverage that tests source itself and we avoid using bundling tools, therefore we don't build during testing.
We add the following packages on Mocha itself. `@babel/register` to transpile our sources (except for node_modules) and `svelte-test-register` to compile svelte files.
It would be helpful if plugin JS files were already compiled, but if it's a hassle then I guess I can just mock the import that causes me issues.

**Comment by ItalyPaleAle** [comment]
Would changing the extension of the files from `.js` to `.jsm` help? That I may be able to do hopefully without breaking too much stuff.

I am not sure I understand your testing setup, but it seems a bit unusual (to not compile before running tests). I am not able to change how this module is distributed: there are explicit reasons why I'm publishing a source (`.svelte` file and `.js` for modules) and not compiled files.

**Comment by DimitrisRK** [comment]
> Would changing the extension of the files from `.js` to `.jsm` help? That I may be able to do hopefully without breaking too much stuff.
> 
> I am not sure I understand your testing setup, but it seems a bit unusual (to not compile before running tests). I am not able to change how this module is distributed: there are explicit reasons why I'm publishing a source (`.svelte` file and `.js` for modules) and not compiled files.

My team have always had a testing setup for server-side node sources using grunt + mocha + nyc and wanted to use the same setup for client-side. Our discussion makes me realize that the best solution is to build client sources before testing but I also need to export a single coverage report in the case of CI since we have a monorepo that relies on it.

Please don't bother doing any changes. I believe I need to improve my testing setup for clients.
Thank you very much for responding to my question! I appreciate your help!
