### ISSUE TITLE
Does it possible to "bind:this" to routes define? or how can i get component-instance with svelte-spa-router

### ISSUE THREAD

**Issue by miepian** [ItalyPaleAle/svelte-spa-router#237]
I have A.svelte,B.svelte,use svelte-spa-router to switch into router-view of App.svelte.I want click an button in App.svelte to call function(with parameters) in A.svelte(or B.svelte)when it is current view. but I can not found anywhere to "bind:this".

**Comment by ItalyPaleAle** [comment]
You can't use `bind:this` because every component is a child of the `Router` component and not of your `App`.

You will probably need to use some other way to communicate, depending on your code.
