### ISSUE TITLE
?options=on#

### ISSUE THREAD

**Issue by JoFont** [ItalyPaleAle/svelte-spa-router#24]
Hello, I don't know if it has to do With the router, Svelte or the browser itself but a few days ago I started getting my url start with ...domain...**?options=on#/**... It is not spontaneous, it's when I do certain actions in a site, It reloads with the url like that. Any clues as to why It may be happening?

FYI: I Chose no to include snippets because I don't know where to look and the project is quite big by now, If you'd like to take a look at something specific just ask, otherwise I could invite you to the repo.

Thank you very much for your help and I guess I crack open a Pale Ale in the mean time ;)

**Comment by ItalyPaleAle** [comment]
without more context and info (and possibly code), I can’t help sorry!

**Comment by luisbello30** [comment]
@JoFont it is posible when you use `<form>` and not use `<form on:submit|preventDefault={handleSubmit}>`

when you try to do this: 

```javascript
<script>
    function loginClick() {
        // somethings ...
    }
</script>

<form>
     // somethings ...
    <button class="button" on:click={loginClick}>Login</button>
</form>
```

The right way can be this: 

```javascript
<script>
    function loginClick() {
        // somethings ...
    }
</script>

<form on:submit|preventDefault={loginClick}>
    // somethings ...
    <button class="button" type=submit>Login</button>
</form>
```

**Comment by JoFont** [comment]
Hello @luisbello30! Yes, you're totally right, that was the solution to the issue.
Thank you very much for the help! 🥇
