### ISSUE TITLE
Remounting component when using NestedRoutes

### ISSUE THREAD

**Issue by gomeslucasm** [ItalyPaleAle/svelte-spa-router#240]
Hello,

I'm using two routes that return the same component in a nested route:

```
routes.set(
  '/', wrap({
    asyncComponent: () => import('Component.svelte'),
  }),
)

routes.set(/^\/tickets(\/(.*))?/, wrap({
  asyncComponent: () => import('Component.svelte'),
}))
```
The problem is that when I access ' \ ' and after that '\tickets\ the components remount.

How could I solve this?

**Comment by ItalyPaleAle** [comment]
Yes, this is by design, because they're two different routes.

What you can do is to use a single RegExp (and you're already using one) that matches both routes. Something like:

```js
routes.set(/^(\/tickets(\/(.*))?)|(\/)|$/, wrap({
  asyncComponent: () => import('Component.svelte'),
}))
```

https://regex101.com/r/qA0YhY/1
