### ISSUE TITLE
More precise explanation of routeEvent?

### ISSUE THREAD

**Issue by radio-miskovice** [ItalyPaleAle/svelte-spa-router#242]
Hello,
I have a Login component routed by Router. When I dispatch event 'login' it is never received by the router.

**App.svelte**
```typescript
<script>
  import Router from "svelte-spa-router";
  import { link, replace } from "svelte-spa-router";
  function handleLogin( event ) {
    console.log( 'Login event received');
    console.log(event);
    isLoggedIn = true ;
  }
</script>
...
  <Router {routes} on:login={handleLogin} />
...
```

**Login.svelte**
```typescript
...
  function submitLogin() {
    let apiUrl = "/login";
    message ='' ;
    console.log("Invoking LOGIN...");
    let body = new FormData(loginFormElement);
    console.log(body);
    fetch(apiUrl, { method: "POST", body }).then((response) => {
      if (response.status == 200) {
        return response.json();

      }
    })
    .then( data => {
        if( data.status == 'OK' )
        dispatch('login', {});
        pop(); 
    })
    .catch( err => console.log(err ))
    ;
  }
...
```

In Chrome developer tools I can trace the program to the line with `dispatch('login', {})`, but in App.svelte the event never fires `handleLogin()`.

Does it mean that the event dispatched must be named 'routeEvent'? In the documentation it is unclear whether *routeEvent* is an example of an event, or if it is a strict requirement.

**Comment by ItalyPaleAle** [comment]
Yes it must be called `routeEvent`. If you have multiple events, you can then "route" them in the event handler.
