### ISSUE TITLE
Routes regex matching

### ISSUE THREAD

**Issue by GioPat** [ItalyPaleAle/svelte-spa-router#244]
First of all I would like to do my congratulations for this amazing package and it's cool to see that it is coming from an Italian colleague 🔥 

I have the following routes:
```ts
import Users from "./components/routes/Users.svelte";
import Home from "./components/routes/Home.svelte";
import Deadlines from "./components/routes/Deadlines.svelte";

export default {
  '/': Home,
  '/users*': Users,
  '/deadlines*': Deadlines,
  '*': Home,
}
```
and the following Router usage:
```ts
<script lang="ts">
  import routes from "./routes";
</script>
<Header />
<main>
  <Router routes={routes}/>
</main>
<Footer />
```

When I access the url: `http://localhost:5000/#/users` I get redirected to the User component.
When I access  `http://localhost:5000/#/users/2`, for example, I get redirected to the Home and the last wildcard gets hit.
In the canonical regex behavior I should always see the User component.
Am I (or am I doing something) wrong?

Thanks

**Comment by ItalyPaleAle** [comment]
The `*` character works differently from the behavior of tools like grep. The router uses [regexparam](https://github.com/lukeed/regexparam) internally to convert strings into regular expressions, and that library implements `*` only in the context of a full path (so after a `/`).

What you want to accomplish can't be done with a single string. You have 2 options:

1. Define your routes in a Map object and use a regular expression that matches all cases you want, like `^\/users(?:\/(.*))?`
2. Create two separate routes that both point to the `User` component: `/users` and `/users/*`

(See also https://github.com/ItalyPaleAle/svelte-spa-router/issues/133 )
