### ISSUE TITLE
Global pre-conditions

### ISSUE THREAD

**Issue by petermakeswebsites** [ItalyPaleAle/svelte-spa-router#247]
Is it possible to have pre-conditions apply to all router actions?

I would like to create a continue-or-cancel dialogue to prevent a user from navigating elsewhere in the app while there is unsaved data they're working on. Everything works well on the side, but at this point, I have to make a wrapper function around all pop/pushes in the navigation. Pre-conditions look nice, but I believe I would have to specify the same pre-condition for every single route. Is it possible to make a global pre-condition for any pop/push or navigation event?

Thanks!

**Comment by ItalyPaleAle** [comment]
The thing about pre-conditions is that they are executed after the navigation. If the pre-condition fails, no route is loaded (so you'd see a "blank" page). You can certainly implement a navigation that goes back to the previous page, but the components may be un-mounted in the process.

For your use case, I'd implement something that happens before the navigation happens. For example, a Svelte Action that is added to `a` tags and that can prevent the navigation from happening in the first place.

As for global pre-conditions, I am not supportive of that. When designing the APIs for this router, I'm more concerned with simplicity than in avoiding repetition. One should be able to look at the routes object and immediately know what routes are defined and what are their conditions/etc. A global config would complicate the APIs quite a bit.

**Comment by petermakeswebsites** [comment]
Thanks for your clarification, Alessandro. I understand where you're coming from.

For anyone stumbling here from Google, I made a simple workaround. I set a listener to the hash change. 

```typescript
let currentHash = location.hash
let tmpHash = location.hash
addEventListener("hashchange", (e) => {
    if (pageEditing) { // Bypass if we're not editing anything
        if (currentHash == location.hash) return // The event gets called when we set location.hash to back to currentHash, so this catches it

        // Set the requested location into temp, and set the current location to the one we're about to leave
        tmpHash = location.hash
        location.hash=currentHash

        someKindOfPrompt.then((staying) => {
                if (staying) return
                currentHash = tmpHash
                location.hash=tmpHash
                tmpHash = location.hash
            }).catch(() => {
                // ...
            })

    } else {
        currentHash = location.hash // Update currenthash location with new page
    }
})
```

**Comment by ItalyPaleAle** [comment]
There's a couple of issues I can see with that approach.

First, svelte-spa-router works by binding to the `hashchange` event. So you need to always make sure that your event listener is added before the router's (this could be done safely by adding the event listener before the router is initialized). Not necessarily a deal-breaker, but something to keep in mind.

The biggest problem I see is that you're setting `location.hash`. This creates a new entry in the history stack, so it could mess up the back button. If you do want to proceed with this approach, you can use `history.replaceState` instead–see how the router does it: https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Router.svelte#L147

I would still recommend an approach that looks at navigation events and blocks them from happening directly.
