### ISSUE TITLE
Single route guard on multiple routes

### ISSUE THREAD

**Issue by girishnuli** [ItalyPaleAle/svelte-spa-router#249]
Assuming we have 2 areas in an app that are defined in separate files and then merged together:
```
const adminRoutes = {
  page1: 'admin-page-1',
  page2: 'admin-page-2'
}

const appRoutes = {
  page1: 'app-page-1',
  page2: 'app-page-2'
}

const routes = {
 ...adminRoutes,
...appRoutes
}

<Router {routes} />
```

Is there a way to define a **common route condition on adminRoutes** instead of every single route in adminRoute? This is helpful where there are many routes in admin section, but we need just a single condition to check if a user is authenticated or not. Otherwise we will be simply duplicating a lot of code by defining the condition on each individual route. Thanks.

**Comment by ItalyPaleAle** [comment]
Nope, there's no way to define a common route condition. That would complicate the APIs too much.

I agree there's some repetition, but you can define the route condition function once and re-use that.
