### ISSUE TITLE
Change routes file, app reloads, can't access changes?

### ISSUE THREAD

**Issue by graemedouglas** [ItalyPaleAle/svelte-spa-router#25]
Hey there,

I've installed this package with npm and imported it in my `App.svelte` file. Created a `src/routes.js` as in the example, with the following config:

```
import Dashboard from './components/pages/Dashboard.svelte'
import Register from './components/pages/Register.svelte'
import Login from './components/pages/Login.svelte'

const routes = {
	'/': Dashboard,
	'/register': Register,
	'/login': Login
};

export default routes;
```

Import the file in my App.svelte file, everything works! I then edited `src/routes.js` to be like the following:

```
import Dashboard from './components/pages/Dashboard.svelte'
import Register from './components/pages/Register.svelte'
import Login from './components/pages/Login.svelte'
import CreateNewOrganization from './components/pages/CreateNewOrganization.svelte'

const routes = {
	'/': Dashboard,
	'/create_organization': CreateNewOrganization,
	'/register': Register,
	'/login': Login
};

export default routes;
```

No compiler errors for the new component, but it won't show the new route! Tried restart `npm run dev` and still nothing. I also tried editing an existing route as follows:

```
import Dashboard from './components/pages/Dashboard.svelte'
import Register from './components/pages/Register.svelte'
import Login from './components/pages/Login.svelte'

const routes = {
	'/': Dashboard,
	'/register2': Register,
	'/login': Login
};

export default routes;
```

and still, I have to navigate to `/regsiter` to get to the registration component.

I tried clearling my cookies/localstorage just for kicks, no change in behaviour.

Any ideas?

**Comment by ItalyPaleAle** [comment]
There might be a JS error in one of your routes? Does the browser’s console say anything?

**Comment by graemedouglas** [comment]
No console errors, no errors when running `npm run dev` either.

**Comment by ItalyPaleAle** [comment]
I don’t have enough context to reproduce this, I’m afraid. Could be an issue with rollup/webpack?

Anyways, good that it works
