### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by jeasoncc** [ItalyPaleAle/svelte-spa-router#250]
Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'es2022', 'esnext', 'commonjs', 'amd', 'system', 'umd', 'node12', or 'nodenext'.ts(1323)

Overview.svelte' is not a module.ts(2306)

**Comment by ItalyPaleAle** [comment]
As the message says, if you want to use dynamic imports you need to set TS to use the correct modules.

This is not an issue specific to this library.
