### ISSUE TITLE
Identifier 'location' has already been declared

### ISSUE THREAD

**Issue by xland** [ItalyPaleAle/svelte-spa-router#257]
svelte:3.46.4
svelte-spa-router:3.2.0
error info:
```
Uncaught SyntaxError: Identifier 'location' has already been declared
```
App.svelte
```js
<script>
  import Router from "svelte-spa-router";
  import { routes } from "./routes";
</script>

<Router {routes} />

<style lang="scss">
</style>
```

routes.ts
```js
import Login from "./Login.svelte";

export let routes = {
  "/login": Login,
};
```

When I comment out this sentence,The error is gone.
node_modules\svelte-spa-router\Router.svelte
```ts
export const location = derived(loc, ($loc) => $loc.location);
```

**Comment by ItalyPaleAle** [comment]
Hi @xland the code is working fine for me and the issue may be somewhere else in your codebase. I will need more information to be able to replicate this error.

**Comment by ItalyPaleAle** [comment]
Closing for now. Please feel free to re-open if you still experience this issue.

**Comment by xland** [comment]
Sorry for late reply.
Close it is ok.
I can not supply more info to replicate this error.(My code is complicated and is based on Electron)
