### ISSUE TITLE
Is it possible to prevent URLs from being initialized when the browser is reloaded?

### ISSUE THREAD

**Issue by nrikiji** [ItalyPaleAle/svelte-spa-router#258]
Thanks for the great library.

Is it possible to prevent the parameters after the hash from being removed and the root URL from being displayed when the browser is reloaded?

http://localhost:8080/#/?tab=1
For example, if you reload your browser with this URL

http://localhost:8080/#/
This URL will be displayed.

Is there something wrong with my program?

**Comment by ItalyPaleAle** [comment]
The router doesn't alter the URL in that way. Do you have any other code that may be interacting with the hash?

**Comment by nrikiji** [comment]
Thanks, now that I know it's not a svelte-spa-router problem, I'll look into it here.

**Comment by ItalyPaleAle** [comment]
Ok. If it ends up being a bug here, feel free to reopen with details :)
