### ISSUE TITLE
Highlight active links - could we have pure function for programmatic use?

### ISSUE THREAD

**Issue by dejsan** [ItalyPaleAle/svelte-spa-router#261]
Hi and thank you for awesome repo!

I have a case where my element isn't the DOM element and I need programmatically to check if the location is currently active.

Is it possible to have something like:

```
<script>
import active from 'svelte-spa-router/active';
const isActivePage = active(path);
</script>
<CustomComponent class="{isActivePage ? 'activeClas' : 'inactiveClass'}">
```

**Comment by ItalyPaleAle** [comment]
Sorry for the delay in answering this. I would subscribe to the [`$location` readable store](https://github.com/ItalyPaleAle/svelte-spa-router#getting-the-current-page) to get the current page
