### ISSUE TITLE
Use with sveltekit

### ISSUE THREAD

**Issue by pjebs** [ItalyPaleAle/svelte-spa-router#262]
Is there a way to use this svelte kit to make spa with hash based routing?

**Comment by ItalyPaleAle** [comment]
This is not compatible with Svelte Kit sorry :( the first issue is philosophical: Svelte Kit aims to be “battery included” and already has its own routing logic.

**Comment by chmac** [comment]
Firstly, thanks for svelte-spa-router, it's making my life a lot easier!

I'm able to get it running (so far at least) with svelte kit. But the key was I needed to add `export const ssr = false` to my root template. I'm not trying to mix and match, so I only have a root layout and a route page, and then svelte-spa-router takes over. I share all this in case anyone else finds this issue with the same question. Of course, as @ItalyPaleAle said, it's not offically supported!
