### ISSUE TITLE
Change global styling conditionality depending on the location

### ISSUE THREAD

**Issue by dtsmarin** [ItalyPaleAle/svelte-spa-router#263]
I'm trying to change the background color of the whole window when I go to a certain route. I tried an if block with $location but it didn't work.

**Comment by ItalyPaleAle** [comment]
Can you share exactly what you tried?

What I'd do is, use an [`onMount()`](https://svelte.dev/tutorial/onmount) function in your component and change the body's style in there, then revert that inside [`onDestroy()`](https://svelte.dev/tutorial/ondestroy)

Closing as this is not necessarily an issue with the router but more like a question. But feel free to respond if you want to discuss further!
