### ISSUE TITLE
```restoreScrollState``` does not work when page is scrolled only horizontally

### ISSUE THREAD

**Issue by Jan-Kruse** [ItalyPaleAle/svelte-spa-router#266]
The scroll state is not restored, when ```window.scrollX > 0``` and ```window.scrollY = 0```. This is caused by the following condition in ```Router.svelte```:

```js
if (event.state && event.state.__svelte_spa_router_scrollY) {
    previousScrollState = event.state
}
```

It should be changed to something like:

```js
if (event.state && (event.state.__svelte_spa_router_scrollY || event.state.__svelte_spa_router_scrollX)) {
    previousScrollState = event.state
}
```

**Comment by ItalyPaleAle** [comment]
Thanks for reporting this :) Would you be interested in opening a PR?

**Comment by Jan-Kruse** [comment]
@ItalyPaleAle PR #268 is waiting for merge
