### ISSUE TITLE
Having a router inside of another router

### ISSUE THREAD

**Issue by joshnwosu** [ItalyPaleAle/svelte-spa-router#267]
How can I achieve this?
```
{
		path: "/",
		component: Music,
		children: [
			{
				path: "/",
				component: Songs,
			},
			{
				path: "/artists",
				component: Artists,
			},
			{
				path: "/albums",
				component: Albums,
			},
		],
	},
	{
		path: "/about",
		component: About,
       },
}
```

**Comment by carbogninalberto** [comment]
Hi, what you want to achieve is a nested route; is that correct?
You can find it in the doc [here](https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#nested-routers)

**Comment by joshnwosu** [comment]
> Hi, what you want to achieve is a nested route; is that correct? You can find it in the doc [here](https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#nested-routers) under Nested routers chapter :)

Exactly what I was looking for. Thanks a ton!
