### ISSUE TITLE
Using push outside svelte files (js files)

### ISSUE THREAD

**Issue by Asami-1** [ItalyPaleAle/svelte-spa-router#269]
Hi,

Is it possible to import {push} or any other methods from "svelte-spa-router" and use them in js files ? 
Those methods don't do anything outside svelte files, am i missing something ?

Thank you very much.

**Comment by ItalyPaleAle** [comment]
It's possible only if you have a svelte compiler installed in your project.

I'd also add that this project is licensed under MIT, so you can, respecting the license, just copy/paste those methods in your own JS code :)
