### ISSUE TITLE
Ensure hash is present in URL

### ISSUE THREAD

**Issue by talwat** [ItalyPaleAle/svelte-spa-router#272]
Hi!

Is there any way to redirect or change the URL if the hash is not present?

For example, if they go to `mywebsite.com` it will redirect them to `mywebsite.com/#/`?

And if they go to `mywebsite.com/#` it will also redirect them to `mywebsite.com/#/`.

**Comment by ItalyPaleAle** [comment]
You can certainly do that in your app's "init" code!

For example, in the [`app.js`](https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/examples/basic-routing/src/main.js) file (or whatever your "main" file is), you can `import {location, replace} from 'svelte-spa-router'` then get the value of `$location`, and if it's not `#/`, then use `replace()` to redirect the user.
