### ISSUE TITLE
Page doesn't update when navigating within the same route using different params

### ISSUE THREAD

**Issue by AbsohAbsoh** [ItalyPaleAle/svelte-spa-router#274]
If I have a route such as: `'blog/:id: Blog'` and I navigate to blog/3, via a link/href from blog/2, the route doesn't update. I have tried using traditional links as well as the imperative `push` and `replace` functions provided by this library.

**Comment by ItalyPaleAle** [comment]
It’s definitely a scenario that could work.

are you able to provide more info? What browser are you using? Can you perhaps share some code to reproduce this as MVP?

**Comment by StevenRenaux** [comment]
Maube this one could help you.

https://github.com/ItalyPaleAle/svelte-spa-router/issues/14

I had the same issue and finally had a look in the closed ones.

**Comment by MerlinB** [comment]
To solve this you can force re-render the component inside of a parent component when the params change.

```svelte
<script>
  import SomeComponent from "SomeComponent.svelte"

  export let params
</script>

{#key params.someParam}
  <SomeComponent someParam={params.someParam} /> // All code from the route moved into this component
{/key}
```

**Comment by algaly** [comment]
Try to replace your **a tag** with **button** and use the **push** method.
**Worked** for me! (**even with animation**)
