### ISSUE TITLE
when visiting the homepage, http auto redirects to https

### ISSUE THREAD

**Issue by resession** [ItalyPaleAle/svelte-spa-router#275]
whenever i go to `http://somepage.com/`, it auto redirects to `https://somepage.com`. i tried a new svelte project and i can confirm that svelte by itself works and does not auto redirect. but when i use svelte-spa-router, this auto redirect problem happens. any ideas?

i don't want it to redirect.

**Comment by ItalyPaleAle** [comment]
I don’t think this is the router, as I don’t believe there’s any code path that would cause this. What platform is your app running on? That would be the first thing I’d consider.

**Comment by resession** [comment]
@ItalyPaleAle you are correct, it is not svelte-spa-router, it is gundb. i commented out `<Router {routes}>`, half of the routes uses gundb, the routes without gundb works. i will close this out.
