### ISSUE TITLE
use:active breaks when removing a link from an #each

### ISSUE THREAD

**Issue by TorstenDittmann** [ItalyPaleAle/svelte-spa-router#28]
use:active breaks when removing a link from an #each array.

My example:

```
{#each testData as testItem}
    <li use:active={testItem.link, 'active' }>
        <a href={testItem.link} use:link>{testItem.name}</a>
        - 
        <i on:click={() => removeData(testItem.id)}>X</i>
    </li>
{/each}

let testData = [
    {
        id: 1,
        name: "link",
        link: "/hello/1"
    },
    {
        id: 2,
        name: "link2",
        link: "/hello/2"
    },
    {
        id: 3,
        name: "link3",
        link: "/hello/3"
    },
];

function removeData(id) {
    testData = testData.filter(data => data.id != id);
}
```

After a link in the array is removed, the active state remains frozen on the current one and does not change anymore. 

Conversely, when a link is added, everything still works. Only if a link with a use:active is removed.

Right now I am looking into the problem...

I forked the example from this project and added code where the error occurs:
https://github.com/TorstenDittmann/svelte-spa-router/tree/master/example

**Comment by ItalyPaleAle** [comment]
Version 1.2.1 is now on NPM with this fix. Thanks for your contribution!

**Comment by TorstenDittmann** [comment]
You are welcome!
