### ISSUE TITLE
Possible to leverage the routing to work with table pagination?

### ISSUE THREAD

**Issue by JustBarnt** [ItalyPaleAle/svelte-spa-router#280]
Is it possible for the router to for table pagination so the user could use the next or back buttons in the browser or the associated keyboard commands to go back and forth in the history stack? 

So far all my efforts result in a new page loading that doesn't exist.

**Comment by ItalyPaleAle** [comment]
Can you give an example of the routes you want to create? Are you asking about navigating within the same page?

**Comment by JustBarnt** [comment]
I am trying to get the back/forward buttons to work with a table that has pagination on it. I have a url for the table itself. 

`localhost:XXXX/#/licenses/1` <-- starting page for the table one page 1

When I hit the next I want the route to update, which it does. It will count up for each additional page.

But what I am trying to achieve is that hitting forward or back browser buttons or using the corresponding keybinds: "alt + arrow" it will go to the route and also show the correct data. 

Which it current updates the url as expected like it does with the other pages. But it does not load the new data.

**Comment by ItalyPaleAle** [comment]
Could this be a similar issue to this? https://github.com/ItalyPaleAle/svelte-spa-router/issues/274

I think I need to add this to the docs.

**Comment by JustBarnt** [comment]
@ItalyPaleAle I will give this a try when I get into work today. Thank you!

**Comment by JustBarnt** [comment]
@ItalyPaleAle Sorry it took a couple days to get back to you, I had to refactor a bit and had some other things come up. But this indeed was a successful and easy solution now that I know what needs to be done. I will be closing this issue! Thank you.

**Comment by ItalyPaleAle** [comment]
Thanks for confirming!
