### ISSUE TITLE
If I want to go to the login page in the sidebar + SPA form, is it possible with route guard?

### ISSUE THREAD

**Issue by Neptunium1129** [ItalyPaleAle/svelte-spa-router#297]
my sidebar example 

https://sophana.github.io/svelte-spa-router-sidebar/docs/

It is very similar based on this project

![image](https://user-images.githubusercontent.com/32185134/231815811-436620b7-efa6-4929-9e76-eef94bba2b6d.png)

![image](https://user-images.githubusercontent.com/32185134/231816290-d6b24ab6-8cc2-42b3-87c0-12c73229ebe1.png)

but When logging out, the login page appears within a slot instead of appearing standalone.

Is it possible to transition to the LoginPage when logging out?

**Comment by ItalyPaleAle** [comment]
Nice, thanks for sharing @Neptunium1129 ! Glad I could be of help :)

PS: Because there's no action for me to do on this issue, I'm going to close it for now

**Comment by ItalyPaleAle** [comment]
I see the images now, reopening

**Comment by Neptunium1129** [comment]
![image](https://user-images.githubusercontent.com/32185134/231818060-a719a043-c0ea-41d0-aad0-25a2103f4abe.png)
 ```javascript
{#if sessionCheck == false}
  <!-- content here -->
  <NmsLogin on:sessionCheck={fnSessionCheck}></NmsLogin>
{:else}
  <!-- else content here -->
  {#await fnLoginCheckAxios()}
      <div>LOGIN...</div>
  {:then res}
    {#if res.data.data.customerYn=="Y"}
        <NmsCustMain on:sessionCheck={fnSessionCheck} {fnSessionCheck} loginUser={res.data.data}>
		<span slot="content">
			<Router {routes} >
			</Router>
		</span>
        </NmsCustMain>
    {:else}
        <NmsMain on:sessionCheck={fnSessionCheck} loginUser={res}}>
            <span slot="content">
                <Router {routes} >
                </Router>
            </span>
        </NmsMain>
    {/if}
  {:catch error}
      <div>LOGIN FAIL...</div>
  {/await}
{/if}
```

When the logout button is clicked, the user is directed to a standalone page. However, if authentication is interrupted in the middle, the login page is displayed within a slot.
