### ISSUE TITLE
Is this not possible in routeLoaded?

### ISSUE THREAD

**Issue by Neptunium1129** [ItalyPaleAle/svelte-spa-router#299]
![image](https://user-images.githubusercontent.com/32185134/232307668-17d0cd69-6d65-4ef1-85d8-84714df4594c.png)

If there is no way, I want to find an alternative.

**Comment by ItalyPaleAle** [comment]
It's very hard for me to help without seeing more context.

What I'd normally recommend is to use route pre-conditions to redirect users to your #login endpoint if needed: https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#route-pre-conditions

**Comment by Neptunium1129** [comment]
app.svelte is branched for three conditions: customer, developer, and external developer. However, I thought that it is not suitable for preconditions because it only applies to true or false.

**Comment by Neptunium1129** [comment]
![image](https://user-images.githubusercontent.com/32185134/232359567-efce8903-b5f5-4331-9905-570e9f57ad91.png)

**Comment by ItalyPaleAle** [comment]
You can return false from the condition function, then listen to the “conditionFailed” event to redirect the user (use the replace() method from this router)

**Comment by Neptunium1129** [comment]
Thansk!
