### ISSUE TITLE
Feature request: Svelte 4 support

### ISSUE THREAD

**Issue by JeviScript** [ItalyPaleAle/svelte-spa-router#302]
Hey! Just wanted to ask if there is a plan to update the lib to support Svelte 4? As it stands it does not compile for Svelte 4 giving typescript errors when using wrap function. Current workaround is typecast it like so:

```
  const routes = {
    "/home": wrap({
      asyncComponent: () => import("./routes/Home.svelte") as Promise<{default: typeof SvelteComponent}>,
}
```

**Comment by mikeychowy** [comment]
I'll maybe open a PR for svelte 4 support when I have the time, the migration script should be doing all the heavy lifting so it'll be fast

**Comment by ItalyPaleAle** [comment]
👋 I think we definitely do want svelte 4 support.

I will not be able to look into this until next weekend at the earliest. But I welcome any PR!

It may be a good opportunity to also go through with some breaking changes.

**Comment by mikeychowy** [comment]
created a [PR here](https://github.com/ItalyPaleAle/svelte-spa-router/pull/303)

**Comment by boustanihani** [comment]
Please merge and support Svelte-4.

Svelte-5 is also on its way :)

**Comment by DirkRaeder-KDO** [comment]
@ItalyPaleAle any update on this?

**Comment by ItalyPaleAle** [comment]
@mikeychowy are you still planning on working on this?

**Comment by carbogninalberto** [comment]
I opened the PR https://github.com/ItalyPaleAle/svelte-spa-router/pull/309 bumping the changes from @mikeychowy

**Comment by carbogninalberto** [comment]
@ItalyPaleAle did you have time to take a look?

**Comment by ItalyPaleAle** [comment]
Thanks @carbogninalberto for the PR. I fixed the linter issues and merged it.

I am going to do some additional validation tomorrow and then cut the release

**Comment by ItalyPaleAle** [comment]
Version 4.0.0 has been released with Svelte 4 support!
