### ISSUE TITLE
How can I protect a route such that a user won't be able to get to it unless they are logged in?

### ISSUE THREAD

**Issue by chovy** [ItalyPaleAle/svelte-spa-router#32]

**Comment by ItalyPaleAle** [comment]
This is depending on your application, how you manage authentication, etc. In general, frontend apps are all public (it's all client-side code); it's when they fetch data from the server that they need to prove they're authenticated...

I'm afraid this question is beyond the scope of this project.

Additionally, please note that GitHub issues are primarily for reporting issues with the router itself, and I'm not able to provide free consulting services.

**Comment by chovy** [comment]
is there a way to execute a function before a route is triggered?

Like in vue-router, you can do `router.beforeEach(checkForAuth); I think I would need something like that to do what I want.`

**Comment by ItalyPaleAle** [comment]
See #23
