### ISSUE TITLE
active doesn't work on anchor container

### ISSUE THREAD

**Issue by chovy** [ItalyPaleAle/svelte-spa-router#39]
My design requires I have markup like this:

`<li class="active"><a href="/pricing">Pricing</a></li>`

However this doesnt' seem to work with `use:active`

`<li use:active={'/pricing', 'active'}><a href="/pricing" use:link>Pricing</a></li>`

The class actuall shows up correctly, but I'm not seeing my css changes for .active.

I tried global and also in component style tag.

//_colors.css

```
root {
    --main-nav-link-active: #212226;
    --main-nav-link-active-border: #1D3D30;
}


:root(li.active) {
    background-color: var(--main-nav-link-active);
    border-color: var(--main-nav-link-active-border);
}
```

and in the component:

```
    li.active {
        border-width: 1px;
        border-style: solid;
        
    }
```

**Comment by TorstenDittmann** [comment]
Would you mind creating a REPL where this behavior occurs?

Because in my current project I am doing something exactly the same. Chrome inspector might give some information on what is going on with the css.

**Comment by chovy** [comment]
I think its because I'm using postcss.

the rule is dropped i believe. What REPL should I use?

**Comment by ItalyPaleAle** [comment]
I'm not familiar with PostCSS, but if the class does appear in the HTML tag (when using the inspector), then the use:active action is doing its job correctly.

It's possible that PostCSS is renaming the "active" class to something else, or removing it entirely. It doesn't appear to be an issue with this module however.

PS: Did you solve #38 ? Can I close that?

**Comment by TorstenDittmann** [comment]
You can use this repo at https://svelte.dev/repl/ with import Router from 'svelte-spa-router'; 

Yeah, it could be a problem caused by postcss.

**Comment by chovy** [comment]
yeah. i think postcss is just too much god damn work. lol

And no when I refresh my pricing page I still go to /login

**Comment by ItalyPaleAle** [comment]
With svelte, usually postcss isn’t strictly necessary because the framework includes the same functionality (CSS scoped to a component).

As per the other issue, can you please provide a REPL there?

**Comment by chovy** [comment]
postcss lets me use future versions of css. its like babel for css. that's why I tried using it.
