### ISSUE TITLE
[Feature Request] Object based route guards

### ISSUE THREAD

**Issue by aarongeorge** [ItalyPaleAle/svelte-spa-router#44]
Hey there, I've started using your router and I like it a lot, however I really dislike the way route guards are handled.

Taking inspiration from how https://github.com/jorgegorka/svelte-router declares the route guards, I came up with the following helper for the router.

Obviously in my actual app this function is hidden away in the utils file along with the replace and wrap imports.

```html
<script>
    import Router, {wrap, replace} from 'svelte-spa-router'
    import Home from '../pages/home.svelte'
    import Login from '../pages/login.svelte'
    import NotFound from '../pages/not-found.svelte'
    import {isLoggedIn} from '../utils'

    const getRouterConfig = routesObj => {
        const routes = {}
        const redirects = []

        Object.entries(routesObj).forEach(([
            route,
            options
        ]) => {
            if (Object.prototype.toString.call(options) === '[object Object]') {
                if (options.guards) {
                    routes[route] = wrap(options.component, ...options.guards)

                    redirects.push({
                        route,
                        redirect: options.redirect
                    })
                }
            }

            else {
                routes[route] = options
            }
        })

        const conditionsFailed = event => {
            replace(redirects.find(redirect => redirect.route === event.detail.location).redirect)
        }

        return {
            routes,
            conditionsFailed
        }
    }

    const {
        conditionsFailed,
        routes
    } = getRouterConfig({
        '/': {
            component: Home,
            guards: [isLoggedIn],
            redirect: '/login'
        },
        '/login': Login,
        '*': NotFound
    })
</script>

<Router routes={routes} on:conditionsFailed={conditionsFailed} />
```

This works just fine for allowing a single object to declare the route guards and the redirect, however it still falls short as the conditionsFailed doesn't seem to provide a way to let it know which guard failed.

Any updates to make this router more declarative (E.g. My Proposed Router Config Object) would be great, though my helper function is allowing that at the moment so it's not a big issue

However getting some more info as to why the conditionsFailed method was called beyond just the route that was attempted to be navigated to would be great!

**Comment by ItalyPaleAle** [comment]
I see your point. In essence, it would help if conditions could return a custom message, which is then passed to the `conditionsFailed` event?

**Comment by aarongeorge** [comment]
Yeah I was thinking about that part last night. The guards should have individual callbacks, instead of just one redirect. E.g. It might make sense to trigger a notification instead of a redirect if a particular guard fails.

**Comment by ItalyPaleAle** [comment]
It does trigger a notification (the redirect is just an example). I am not going to implement individual callbacks, as that would complicate the APIs too much, but I will look into a way to provide user-defined data in the event. (And that can include a function :) )

**Comment by aarongeorge** [comment]
Awesome, thanks @ItalyPaleAle
