### ISSUE TITLE
are query params supported?

### ISSUE THREAD

**Issue by opensas** [ItalyPaleAle/svelte-spa-router#5]
Is there support for parsing query params like

```
127.0.0.1:5000/#?q=query&page=1&len=20
```

For example I'd like the following route to match /wild and be able to read the params

```
http://127.0.0.1:5000/#/wild?q=query&page=10
```

**Comment by ItalyPaleAle** [comment]
Not built into the library at the moment, but I could consider it (although it would require adding another dependency).

However, you can still work around this by manually parsing the query string. You can get the current hash from the $location store. Then, extract the string after ?, and you can use a library like qs to parse it.

**Comment by ItalyPaleAle** [comment]
An option to help with this scenario while not forcing a heavy dependency on everyone could be having the library split and export the query string but not parse it. And then you could parse it if you want, eg with qs.

Would that help?

**Comment by ItalyPaleAle** [comment]
@opensas I've created a PR... Would this help? https://github.com/ItalyPaleAle/svelte-spa-router/pull/6

I'd like your feedback before merging it!

**Comment by opensas** [comment]
Wow!!!

FLOSS never ceases to amaze me!!!

In less than 24 hs you added the feature, and you are waiting for my
opinion!

As soon as I get home I'll have a look at it, but I'm quite confident in
your skills (I'm barely giving my first steps with svelte)

Thanks a lot

**Comment by ItalyPaleAle** [comment]
Merged! (I take your silence as assent 😬)
