### ISSUE TITLE
Named argument not working. What am I doing wrong?

### ISSUE THREAD

**Issue by zemigpt** [ItalyPaleAle/svelte-spa-router#50]
I know it's probably some newbie mistake of mine, but I'm struggling with named arguments for the last hour without success, so I turned here in search for help, or sanity!

I have a simple SPA.

Defined routes in "routes.js" file like this:

```javascript
import Obra from './Obra.svelte'
import ListaObras from './ListaObras.svelte'
import NotFound from './404.svelte'

const routes = {
    '/obras': ListaObras,
    '/obra/:codigo': Obra,
    '*': NotFound,
}

export { routes }
```

App.svelte looks like this:

```javascript
<script>
  import Router from "svelte-spa-router";
  import { routes } from "./routes";
</script>

<Router {routes} />
```

When I navigate to http://localhost:5000/#/obras/ it works just fine, so the router is working.

When I click on any link or navigate to any address like http://localhost:5000/#/obra/144 it just shows me a 404, and it's not the NotFound one, it's a 404 from the server, meaning it's out of the app and the server is looking for some find and really didn't find the file...
But it shouldn't be looking for any file... the router should handle the URL, shouldn't it?

I'm missing something for sure, but I just can't figure out what...

**Comment by ItalyPaleAle** [comment]
That sounds like an issue with your server maybe? What are you using as server?

**Comment by zemigpt** [comment]
I was using sirv (default svelte npm install) but after reading a comment from you in some other issue I changed to serve.
The error is the same with both...

**Comment by ItalyPaleAle** [comment]
It should work indeed. Can you share the full code to reproduce this (might need to be a separate git repo) or use a REPL? (https://svelte.dev/repl)

Also what browser are you using?

**Comment by zemigpt** [comment]
It must have been something related with bulma or svelma packages. 
In REPL it worked ok, so I started from scratch and it's working...
Go figure...
Thanks and sorry for the time wasted...   ;)
