### ISSUE TITLE
Layouts

### ISSUE THREAD

**Issue by chovy** [ItalyPaleAle/svelte-spa-router#51]
Will you or do you have any plans to add a layout to the Nested routes feature?

**Comment by ItalyPaleAle** [comment]
I’m not sure I understand. What do you mean?

**Comment by chovy** [comment]
Look at svelte-router-spa. They have a main layout where you can include nested routes that render inside the main layout.

**Comment by ItalyPaleAle** [comment]
I'm not familiar with svelte-router-spa (funny name :) ) but at a quick glance they are following a different design.

I am not supporting layouts. The goal of the router is to be as lean as possible, and do as few things as possible. Svelte has a full-blown framework (Sapper) that is very opinionated; my goal is to be the opposite. With this router, routes are just Svelte components with no special requirements, so developers can write the code they want. And the router itself should be very lean (this means less code shipped to your users, and less surface for bugs).

Nested routers are supported, but developers can define their own layout: https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#nested-routers

**Comment by carbogninalberto** [comment]
Layouts can also be achieved by creating a component for each type of layout you want and having the router and the routes as props to it. I made a simple example [here](https://svelte.dev/repl/521a64b02b0b4839bfcc79a4e641471d?version=3.29.4) for whom may find it useful.
