### ISSUE TITLE
Route if routes are set

### ISSUE THREAD

**Issue by rottmann** [ItalyPaleAle/svelte-spa-router#54]
If set routes later and if no routing happend, the router should route with the new routes.
Currently we can not replace or push the same current route.

```
<script>
  import Router from 'svelte-spa-router'
  import SomeView from 'some-view.svelte'

  let routes

  // async fake
  setTimeout( () => {
    routes = {
       '/': SomeView
    }
    // push or replace here will not work
  }, 1000)
</script>

<Router {routes}></Router>
```

Or is it possible to call an init function manually, after setting routes?

According to #53 i want  to set the routes after settings are loaded and user-login is verified.

**Comment by ItalyPaleAle** [comment]
The solution to this is to init the router asynchronously.

In your `App.svelte` component, rather than including `<Router>` right away, put it inside an async/await block that resolves when the routes object is initialized.

You can replace the route object by using reactive statements.

**Comment by rottmann** [comment]
Thanks, i wrapped it in a simple if

```
{#if routes}
  <Router {routes}></Router>
{/if}
```
