### ISSUE TITLE
Should browser click on back or forward execute scripts?

### ISSUE THREAD

**Issue by rottmann** [ItalyPaleAle/svelte-spa-router#55]
I know it is the old browser bfache issue, but should the router detect the back or forward click and execute the scripts again?

On each svelte-file i could do it manually with `window.onpageshow = function(e) {...` (but much boilerplate code)

**Comment by ItalyPaleAle** [comment]
Can you give me an example of what the issue is?

**Comment by rottmann** [comment]
e.g. some edit view, called with `/#/edit/1` press save and after save it pushes automatically to the next record `/#/edit/2`
Then you click the browser back button and you go back to edit 1, but the scripts are not executed.

We can check the changed id and do some stuff, but things like onMount will be ignored.
```
<script>
  export let params = {}

  init() // will not be called here on browser back

  $: if (params.id) {
    init()
  }
</script>
```

**Comment by rottmann** [comment]
I think this problem #56 is similar.

**Comment by chovy** [comment]
Yes, of course it should. That's a fundaemental tenant of usability is don'jt break the back button.

**Comment by ItalyPaleAle** [comment]
This does sound a lot like the issue in #56. To recap, the issue is that the Svelte component isn't unmounted and so Svelte doesn't re-mount the component.

The workaround is to listen on changes on the `$location` store that the router exports, as per the sample code in my example in #56.
