### ISSUE TITLE
"routeLoaded" just for some nested routes, not for all

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#57]
@ItalyPaleAle, I agree with you about the few (amazing) basic features that make this router great.

For the `window.scrollTo(0, 0)` problem (https://github.com/ItalyPaleAle/svelte-spa-router/issues/49) your hint to use the new `routeLoaded` function is great and I'm using it right now like this:

```js
function routeLoaded () {
  window.scrollTo(0, 0);
}
```

But it works for every underlying route.

And maybe this is a new problem now.

How to use it only for some `<Router>` (parent) components?

**Comment by TorstenDittmann** [comment]
Are you using route parameters?

It may be possible, that the routeLoaded() is not firing when a parameter of the url changes.

**Comment by ItalyPaleAle** [comment]
Hey @frederikhors are you trying to listen to `routeLoaded` for some routes only? If so, you can use the first argument passed to `routeLoaded` (event) and check for `event.component` and match it against a list of components you want to execute this for.

**Comment by frederikhors** [comment]
> Hey @frederikhors are you trying to listen to `routeLoaded` for some routes only? If so, you can use the first argument passed to `routeLoaded` (event) and check for `event.component` and match it against a list of components you want to execute this for.

I'm doing it right now. But you also know that it is a bit ugly, right?

**Comment by ItalyPaleAle** [comment]
@frederikhors I have just pushed a better fix to master (will be released in version 2.0) that allows you to pass custom objects using the `wrap` function, even without using route pre-conditions. This is useful to pass custom callbacks that you can execute in the `routeLoaded` event. See the "Advanced usage" doc :)
