### ISSUE TITLE
Able to use with base url?

### ISSUE THREAD

**Issue by nitro52** [ItalyPaleAle/svelte-spa-router#60]
We need to specific a base server side route like `/admin` that will serve up a SPA. We can add a base tag to the page to prefix urls but this breaks the route.  

`<base href="/admin" target="_blank">`

the url ends up as `/admin/#/settings` but the router is matching `/#/settings`. 

Is there a way to get it to work with base tag?

**Comment by ItalyPaleAle** [comment]
At the moment, the router doesn’t care where it’s being deployed as it only looks at what’s after # in the URL.

Your best bet would be to simply don’t add a prefix to your URLs, so they all look like `<a href=“#/somewhere”>`. Alternatively, use the “use:link” action that automatically converts “/somewhere” to “#somewhere”

Did you find any issue with these, any unexpected behavior?

**Comment by nitro52** [comment]
I haven't tried serving it up from our production webserver yet. But i know i've had issues with angularjs in the past but that was without using # urls. so you think in production the route would be /admin/#/settings and internally we just use relative paths like #/something ?

**Comment by ItalyPaleAle** [comment]
Yes it should work without issues as long as all links start with “#/“, or they start with “/“ and you use use:link

**Comment by nitro52** [comment]
Thanks, I'll test it when we are closer to ready and reactivate if needed.
