### ISSUE TITLE
Links to anchors within a page

### ISSUE THREAD

**Issue by classikd** [ItalyPaleAle/svelte-spa-router#62]
Hello,

I would like to use links to go on specific locations on my page, for example a "back to the top" button. But it is always redirecting me to the homepage.
How could i use such links without the router does anything ?

Thank you

**Comment by ItalyPaleAle** [comment]
````
window.scrollTo(0,0)
````

See MDN: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo

You can add this to the `routeLoaded` callback
