### ISSUE TITLE
need to be able to specify multiple active paths

### ISSUE THREAD

**Issue by chovy** [ItalyPaleAle/svelte-spa-router#67]
`<a href="/hello/user" use:link use:active={'/hello/*'}>Say hi with a default className!</a>`

I want to set it active for `/hello` and `/hello/*`. Doing `/hello*` doesn't work

**Comment by ItalyPaleAle** [comment]
This is actually not possible today. The closest thing would be to match “/hello*”, but that would match also the case of /helloworld for example.

A proper solution would require supporting regular expressions there.

I’m adding this to the backlog as a feature request and will implement it in the next release.

**Comment by chovy** [comment]
as i said `/hello*` doesn't work

**Comment by braintapper** [comment]
I'm having a similar issue.

I'm expecting `/hello*` to work with these three cases:

`/hello`
`/hellowithanythingafter`
`/hello/with/anything/after`

My particular use case is that I have a top level nav and sub level nav. My top level nav only highlights `/hello` when using `/hello*`. Once I hit a path for a sub level (`/hello/id`), it's no longer highlighted unless I change the `use:active` path to `/hello/*`

**Comment by drop1down** [comment]
i solved this like so:

import {location} from 'svelte-spa-router'
var path = shortPath($location) //get first part of path
...
<a href="#/users" class:active={path == 'users' || path == 'user'}>Users</a>

**Comment by ItalyPaleAle** [comment]
Support for regular expressions in `use:active` has been added in https://github.com/ItalyPaleAle/svelte-spa-router/commit/1f4788201c605e8fc4a1acccc4d5bbbe51c548a2 :) Sorry this took so long!
