### ISSUE TITLE
use:link behaviour

### ISSUE THREAD

**Issue by braintapper** [ItalyPaleAle/svelte-spa-router#69]
I'm finding that the use:link doesn't appear to behave as expected in all cases:

`<a href="/book/321" use:link>The Little Prince</a>`

Works correctly and points to `#/book/321`

`<a href="/book/{321}" use:link>The Little Prince</a>`

Works correctly and points to `#/book/321`

`<a href="/book/{book.id}" use:link>The Little Prince</a>`

Works incorrectly and points to `/book/321` - it is missing the hash in front

**Comment by ItalyPaleAle** [comment]
Hi @braintapper sorry for the delay. I cannot reproduce the issue, at least with the most-recent versions of Svelte.

Can you please try again with the latest version of Svelte and see if it works? If not, can you share a repro?

**Comment by braintapper** [comment]
Hi @ItalyPaleAle 

I have not revisited that issue for a long time, as my workaround (prefixing my urls with `#`) used fewer characters of code and didn't require an import of `{link}`. I believe I was using svelte-spa-router 1.x when I encountered that issue.

It now appears to work with svelte 3.18.2 and svelte-spa-router 2.0.0. You can close this issue.

**Comment by ItalyPaleAle** [comment]
Thanks for confirming!
