### ISSUE TITLE
custom DOM events won't bubble past <Route />

### ISSUE THREAD

**Issue by AndreLeifert** [ItalyPaleAle/svelte-spa-router#72]
Having tried the first proposed work-around of #42, my findings are very strange.
With HTML like this:
```
<div bind:this={listener} class="width-adjuster mt-3">
  <Index />
</div>
```
and custom event being fired by a component deep inside Index:
```
new CustomEvent('purchase', { bubbles: true, cancelable: false, detail: prjCode }) 
```
Everything works fine - _listener_ gets the event. Once I replace ```<Index />``` by ```<Route />```, everything
**but** the event delivery works fine, which I absolutely don't understand, because the DOM structure
looks exactly the same. Any ideas and possible explanations are very welcome. Thanks!

**Comment by ItalyPaleAle** [comment]
Sorry for the delay. Can you please share a sample repro so I can understand exactly the issue?

**Comment by jcschmidig** [comment]
A very simple approach could be to change the following line in Router.svelte

<svelte:component this="{component}" **on:routeEvent**/ > (lines 208/210)

This way, a component instantiated by the router could dispatch a "routeEvent" event and the component instantiating the router could listen to the this event.

**Comment by ItalyPaleAle** [comment]
@jcschmidig Thanks for clarifying the issue to me and for providing a solution too! wow 😄  I've made the code change and planning to merge into master soon
