### ISSUE TITLE
event to indicate new route loading

### ISSUE THREAD

**Issue by joshua1** [ItalyPaleAle/svelte-spa-router#74]
Is it possible to have another event that gets emitted when navigation to a new route starts . this will make it easy to use modules like progress bar (progressbar.start in onrouteLoading event and progressbar.stop in onRouteLoaded or conditionsFailed events)

**Comment by ItalyPaleAle** [comment]
I think this can be done easily without requiring changes in the router, by changing your views so there's an `{#await}` block inside. It would also offer the best UX.

If you really need to emit an event when the route starts loading, you can do that by using a route pre-condition that always returns true, but has some side effects: https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#route-pre-conditions
