### ISSUE TITLE
buble not working with router

### ISSUE THREAD

**Issue by drop1down** [ItalyPaleAle/svelte-spa-router#78]
i use @rollup/plugin-buble to make js compatible with old browsers
But spa-router do not work with buble

`CompileError: Transforming for-of statements is not fully supported. Use `transforms: { forOf: false }` to skip transformation and disable this error, or `transforms: { dangerousForOf: true }` if you know what you're doing. (353:1)`

```
node_modules\svelte-spa-router\Router.svelte (353:1)
349 :
350 :   // Set up all routes
351 :   const routesList = [];
352 :
353 :   for (const [path, route] of routesIterable) {
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ItalyPaleAle** [comment]
Thanks for finding this. Let me look into this tomorrow for how I can remove the for..of loop

**Comment by drop1down** [comment]
Hm... i tested buble with option to disable forOf...
Unfortunately it was not possible to convert for IE11.
I think this is not spa-router fault (?)

**Comment by hmmhmmhm** [comment]
@drop1down 
Unfortunately, it does not support ie11 from the start of the svelte.
You should use babel & polyfill in your projects.

https://github.com/hmmhmmhm/svelte-spa-template
I recently created svelte-spa-template using babel and polyfill,
which is compatible up to ie 8 with es3 support.

**Comment by ItalyPaleAle** [comment]
@drop1down I've updated the code on master to remove the use of for..of. This _should_ make it more compatible with your situation. Let me know if this works.

However, please note that support for old, deprecated browsers (like IE) is not really in scope for this project, so it's always going to be a best-effort kind of scenario!
