### ISSUE TITLE
How do i bind a variable to a props in an object when its defined in routes?

### ISSUE THREAD

**Issue by cschar** [ItalyPaleAle/svelte-spa-router#79]
Sorry if this is explained somewhere in the docs but it wasn't clear to me.

say i have a component:

```svelte
<script>
	<.... code here ...>
       export let masterList;   //populated in index.js with [1,2,3]
      const routes = {
		'/detail': wrap(Detail, {myList: masterList}),
	}
</script>
<Router {routes}/>
```

am i passing myList in to the "Detail" component as its properties?
similar to if i had defined it in the markup as `<Detail myList={masterList} />` ? ?

I can't get it to work if thats the intended functionality.... 
i've resorted to passing in myList, broken up as elements[1] in a queryhash but i'd like to pass them in as props without resorting to polluting querystring.

[1]:  workaround solution 
```svelte
<script>
  const routes = {
		'/detail/:masterList': Detail
	}
   ...somehwere below
      push("/detail/"+masterList.join("-"))  // mysite.com/#/detail/1-2-3
</script>
```

**Comment by hmmhmmhm** [comment]
If this is a health care that follows the SPA structure
and doesn't need to be accessed again through the address,

You just can use svelte/store,
I think it doesn't need to use routes props,

```js
// optionStore.js
module.exports = writable([1,2,3])
```

```svelte
<!-- page.svelte -->
<script>
    import optionStore from './optionStore.js'
    optionStore.subscribe((changedOption)=>{
        console.log(changedOption)
    })
</script>
```

Or there is a way to convert the object you want to pass
through the function JSON.string() to a string value
when you give query or routes parameters to a page.

**Comment by cschar** [comment]
ok i'll try that, thanks
