### ISSUE TITLE
Component replacement?

### ISSUE THREAD

**Issue by drop1down** [ItalyPaleAle/svelte-spa-router#80]
lets say... i navigate to /#/secret-page
I can add route guards - so in fact i can "push" user away to 403-url (forbidden).
that works

Smarter is to replace component "secret-page" with "403"-component,
without changing url

Is this possible?

**Comment by hmmhmmhm** [comment]
yes you can possible change the component without changing any url,
you just need to use state management,

```svelte
<script>
let isHide = false
</script>

{#if isHide}
    <A/>
{:else}
    <B/>
{/if}
```

**Comment by drop1down** [comment]
OK - one problem with this is, that i need such code for many pages

**Comment by hmmhmmhm** [comment]
what many pages?
what are you trying to render it?

**Comment by drop1down** [comment]
I have different rights.
to load #/view, you need view right
to load #/edit, you need edit right
and so on...

My idea for now:
instead return bool with route pre-conditions.
Additionally it coult return a component (that implicit true at same time).
So we coult override default component with different.

example:

```
	function privRoute(detail) {
		var path = detail.location.split('/')[1]
		if (!$role) { push('/login'); return false } 
		if (!can(path, $role)) { push('/403'); return false }
		return true
	}
```

instead push('/403'),
we could
return Forbidden

**Comment by hmmhmmhm** [comment]
So you want to return the component without returning the route?
I don't know if I understand correctly, but if this is wrong, I apologize first.

If you want to obtain classes from a file with a svelte extension
and give props them dynamically to the class,
the following code can be an example.

https://github.com/hmmhmmhm/svelte-spa-chunk/blob/master/src/index.ts#L5

These components can be dynamically rendered by the <svelte:component> grammar.
https://svelte.dev/tutorial/svelte-component

**Comment by ItalyPaleAle** [comment]
An option is, rather than using route guards, to direct all your routes to a single component (matching `*`). Let's call that component `Gate`.

Inside `Gate` you use a dynamically-loaded component (see [`<svelte:component>`](https://svelte.dev/docs#svelte_component)) to decide if you want to show either of:

- a 403 component
- another Router component (a nested Router) that actually shows the route you want
