### ISSUE TITLE
Hard time testing with @testing-library/svelte and Jest

### ISSUE THREAD

**Issue by feg624** [ItalyPaleAle/svelte-spa-router#81]
Hi: first of all, I like this component a lot! However, I'm having a hard time when trying to test my app with @testing-library/svelte and Jest.

I've followed the instructions on https://dev.to/jpblancodb/testing-svelte-components-with-jest-53h3 to setup the environment, and was able to transform the Router.svelte file (using jest-transform-svelte) with the following configuration on jest.config.js:

`  transformIgnorePatterns: ["node_modules/(?!(svelte-spa-router)/)"]`

The problem I'm facing, that I couldn't figure out how to solve, is that when running the tests I get the following error:

```
    TypeError: regexparam is not a function

      12 | 
      13 |   const routes = {
    > 14 |     '/': Home,
         |                 ^
      15 |     '/login': Login
      16 |   }
      17 | </script>

      at new RouteItem (node_modules/svelte-spa-router/Router.svelte:50:33)
      at instance (node_modules/svelte-spa-router/Router.svelte:136:20)
      at init (node_modules/svelte/internal/index.js:1372:11)
      at new Router (node_modules/svelte-spa-router/Router.svelte:453:3)
      at create_fragment (src/App.svelte:14:17)
      at init (node_modules/svelte/internal/index.js:1387:37)
      at new App (src/App.svelte:78:3)
      at render (node_modules/@testing-library/svelte/dist/pure.js:71:21)
      at Object.<anonymous> (src/App.test.js:8:19)

```

Any clue that may point me into the right direction to solve the issue? I'm wondering whether this has to do with Router.svelte having two <script> sections.

Thanks in advance,

Franco

**Comment by feg624** [comment]
One additional attempt I did is the following. I've replaced on Router.svelte

`import regexparam from 'regexparam'`

by 

`let regexparam = require('regexparam')`

and after that I'm not having the issue any longer. May this be related to eslint processor used on the svelte-spa-router library?

**Comment by hmmhmmhm** [comment]
There is a  few presets are required to properly test grammar such as import in the jest.
https://stackoverflow.com/questions/41324636/how-to-import-jest

Svelte implements the user's import grammar through a library called shimport.
I don't think this issue is a problem with this module.

**Comment by feg624** [comment]
Thanks for the insights. I'm going to follow that direction.

Regards,

Franco

**Comment by ItalyPaleAle** [comment]
Hi @feg624 thanks for reporting this.

I think @hmmhmmhm is on the right track. "import" is a modern ES feature and it might not be supported by your testing framework. However, Svelte works with ES modules and I cannot make the change to use require's instead.

**Comment by feg624** [comment]
Hi all: I got contacted by @kaydwithers about this issue, so I thought it's better to document in here in case someone else needs it.

In order to troubleshoot, I created two files on my project at root level:

**jest.config.js**
`
module.exports = {
  transform: {
    "^.+\\.svelte$": ["svelte-jester", {"preprocess": true}],
    "^.+\\.js$": "babel-jest"
  },
  moduleFileExtensions: ["js", "svelte"],
  testPathIgnorePatterns: ["node_modules"],
  bail: false,
  verbose: true,
  transformIgnorePatterns: [/*"node_modules"*/ "node_modules/(?!(svelte-spa-router)/)"],
  setupFilesAfterEnv: ["@testing-library/jest-dom/extend-expect"]
};
`

**svelte.config.js**
`
module.exports = {
	preprocess: {
    script: async ({ content, filename }) => {
      //Workaround to replace regexparam import by require, otherwise default import doesn''t run with Jest.
      return new Promise((resolve, reject) => {
        resolve({
          code: content.replace(/import regexparam from 'regexparam'/g, "const regexparam = require('regexparam')")
        });
      });
    }
  }
};
`

I don't remember exactly whether these are the only two files that I needed, as I haven't worked on this project for sometime.

Franco
