### ISSUE TITLE
params in empty onMount

### ISSUE THREAD

**Issue by pipboy9000** [ItalyPaleAle/svelte-spa-router#82]
this is where i would usually use this variable, but its empty when accessed from onMount callback.

**Comment by hmmhmmhm** [comment]
I think you didn't export the variable.
I recommend that you run the following these code.

```svelte
<script>
    import { onMount } from 'svelte'
    export let params = {}
    const id = params.id

    onMount(()=> { console.log('check', id) })
</script>
```

**Comment by pipboy9000** [comment]
oh ok i think i figured what i was doing wrong..  i didn't define the param i wanted in the routes.js for this component
