### ISSUE TITLE
<component> was created with unknown prop 'params'

### ISSUE THREAD

**Issue by ItalyPaleAle** [ItalyPaleAle/svelte-spa-router#83]
There's a warning with recent versions of Svelte where components that don't require params cause this message to appear in the console. Will investigate

**Comment by drop1down** [comment]
add this to route-component:
```
export var params
console.log(params)

```

here is something wrong
params should send to components only, if here is params expected and specified

If i have a route like: "user/:id" - params should be sended
If i have a route like "users" - no params should be sended

**Comment by hmmhmmhm** [comment]
Thank you for the update!!

**Comment by ItalyPaleAle** [comment]
I'm going through the other open issues and will issue a release soon :)
