### ISSUE TITLE
Browser back button detection

### ISSUE THREAD

**Issue by rottmann** [ItalyPaleAle/svelte-spa-router#85]
in routeLoaded event. Is it possible?

From within spa it should be easy, cause spa knows when a regular link is clicked, or a page is loaded, or the the remaining possibility the "back button" is clicked.

From outside spa it needs much boilerplate code (e.g. https://stackoverflow.com/questions/25806608/how-to-detect-browser-back-button-event-cross-browser)

**Comment by ItalyPaleAle** [comment]
Since this module is designed for SPAs (hence the name!), I don't think we should implement that amount of code for a very specific scenario.

What is your use case? Maybe there's another solution to the problem?

**Comment by hmmhmmhm** [comment]
I don't know if it will help, but I think I can share one of my developed examples.
https://github.com/hmmhmmhm/svelte-reusable/blob/master/logics/router.ts#L7

The spa router provides a location store. This allows to detect changes route.
This may allow the user to trace back to the previous page.

**Comment by rottmann** [comment]
I slide a page to a subpage (from right to left).
Within the subpage you can press a button and slide back (from left to right), red box in example image. That works.
Example image: https://imgur.com/nlhffaG

But when you press the browsers back button i did not have the direction to slide back.

Yes i know i could set it manually by default from left to right, but when you click a main navigation button, it should not slide, it should fade, but if you press browser back button, it still will slide.

**Comment by ItalyPaleAle** [comment]
I don't think this is something we can help with the router, I'm afraid, sorry!

**Comment by vidstige** [comment]
This should really be implemented. Seems very important. Just as you click a link, you should be able to go back... This is a very basic usage of a browser.

**Comment by ItalyPaleAle** [comment]
Sadly, we cannot get around this, as it's a limitation of the web platform (for privacy reasons)
