### ISSUE TITLE
What about the changelog?

### ISSUE THREAD

**Issue by luisbello30** [ItalyPaleAle/svelte-spa-router#86]
First congratulations for the excellent module, great job

I am attentive to the changes in the library and keep my development updated, it would be very useful to have a record of the changes in the new versions.

I know it's an extra job but I'm sure many would appreciate it

**Comment by ItalyPaleAle** [comment]
You can find the detailed changelog in the Releases tab: https://github.com/ItalyPaleAle/svelte-spa-router/releases

If you’re upgrading from 1.x check out also the UPGRADING file in the repo for how to deal with a few (small) breaking changes
