### ISSUE TITLE
`replace` triggers `DOMException`

### ISSUE THREAD

**Issue by pal03377** [ItalyPaleAle/svelte-spa-router#93]
I noticed my browser did weird things when I used the `replace` function provided by `svelte-spa-router`. In my case the route was somehow duplicated and I tried to reproduce this with a minimal example in the Svelte Repl.

In the Svelte Repl, when trying to navigate with `replace`, just a `DOMException` is thrown. This does not seem to be expected behavior (if I read the documentation correctly):

https://svelte.dev/repl/1321fcda2b774b6e9a13146358ebfcec?version=3.20.1

![issue as screenshot](https://user-images.githubusercontent.com/9006596/76917510-eb12a300-68c3-11ea-901e-5175778d9ff9.png)

**Comment by ItalyPaleAle** [comment]
This is very interesting. I can replicate on the REPL too, but not outside of the REPL. Can you replicate this in a "normal" app?

**Comment by ItalyPaleAle** [comment]
I've done some more debugging and it seems that the issue is with the REPL not fully supporting `Window.history`. Can you confirm if the issue happens outside of the REPL too?

**Comment by pal03377** [comment]
I tried and the issue does not exist outside the REPL. Thanks for investigating!
I still need to track down that route duplication issue, but I will get back to that when I can reproduce it in a minimal environment.

Thanks again!

**Comment by ItalyPaleAle** [comment]
What do you mean with “route duplication issue”?

Anyways, thanks for confirming this is an issue with the REPL. I think I can make a code change to detect that scenario and issue a warning in the console, to make the DX a bit better.

**Comment by pal03377** [comment]
> What do you mean with “route duplication issue”?

In some very specific cases that I could not yet track down (I think it may have something to do with calling `push` or `replace` before a component mount or too fast one after another), I'm getting my route inserted into DOM twice. 

I have a div in which my `<Router { routes } />` lives and each of my routes is wrapped within a `<div>` of its own. Sometimes however, my wrapper has two children that seem to be produced by the `<Router />`.  As soon as I manage to reproduce this in a minimal environment, I will open a new issue for this. It at least seems that doing `await tick()` before `push`ing or `replace`ing helps for now.

**Comment by ItalyPaleAle** [comment]
All navigation method (`push`, `pop`, `replace`) already wait for the next tick: https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Router.svelte#L120

So, `await`'ing in your code *shouldn't* be necessary, unless you are doing some async work yourself...
