### ISSUE TITLE
'Global Route Guards'

### ISSUE THREAD

**Issue by yunfeizhu** [ItalyPaleAle/svelte-spa-router#96]
Hi @ItalyPaleAle 
    I find 'Route pre-conditions' in the document, it is like 'Per-Route Guard' in [Vue-Router#Per-Route Guard](https://router.vuejs.org/guide/advanced/navigation-guards.html#per-route-guard). Does it have a 'Global Route Guards' like 'Global Before Guards' in [Vue-Routerl#global-before-guards](https://router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards)

**Comment by yunfeizhu** [comment]
I have read issue #46. Your idea is to wrap a function and pass in the wrap method for each route. But as a developer who uses Vue a lot, I felt it was important to provide a global routing hook. Is there really no way to intercept every routing request globally?

**Comment by ItalyPaleAle** [comment]
Not at the moment.

My goal is to keep the router's APIs as simple as possible, so the learning curve is minimal. Compare the size of Vue-Router's docs with this one's, for example!

Right now, the `Router` component is configured with just one dictionary that lists all routes, plus an optional event listener. Adding global configurations would require adding a "config" object, and things would start getting more complicated now.

Thus said, if you have any suggestion on how this could be implemented in another way that is less complex, I'm happy to accept a PR!

**Comment by yunfeizhu** [comment]
@ItalyPaleAle  Thank you for the reply,
I am just a beginner of svelte and have only studied for a few days. 😝 I have been using Vue for development, this time there is a new project I want to try Svelte. So some of the ideas about svelte-spa-router that I have are based on Vue-router. Maybe I should spend some time trying to read source code for this project and try to create a PR.
